let queueRows=[],queueLoaded=false,queueError=null,submitBusy=false,queueAudit=null,queueReloadCheck=null,queueTests=null,queueTestsBusy=false,submitToken=null;
const queueStats={enqueued_here:0,restored_groups:0,retried_here:0,cancelled_here:0,commit_failures:0};
function queueMessages(){return queueRows.filter(OutboxVault.active).flatMap(r=>r.messages.map(m=>({id:'out-'+m.id,number:COUNT+m.sequence,mine:true,text:m.text||'',image:false,revision:r.version||1,attachmentId:m.assetId||null,outboxId:r.id,queueState:r.state,queueSequence:m.sequence})))}
function decorateQueueRow(node,m){if(!m.outboxId)return node;node.classList.add('outgoing-pending');const meta=node.querySelector('.meta');meta.textContent='◷ В очереди · не отправлено';node.dataset.outboxId=m.outboxId;return node;}
function queueSummary(){const active=queueRows.filter(OutboxVault.active);return{transport:'NOT_CONNECTED',state:queueError?'error':queueLoaded?'ready':'loading',error:queueError?{name:queueError.name,message:queueError.message}:null,groups:active.length,messages:active.reduce((n,x)=>n+x.messages.length,0),files:active.reduce((n,x)=>n+x.files.length,0),cancelled:queueRows.filter(x=>!OutboxVault.active(x)).length,entries:active.map(r=>({client_message_id:r.id,first_sequence:r.first_sequence,messages:r.messages.length,files:r.files.length,state:r.state,retries:r.retries,server_ack:r.server_ack})),...queueStats,submit_in_progress:submitBusy,audit:queueAudit,reload_check:queueReloadCheck,network_observed_online:navigator.onLine,background_delivery:false}}
function paintQueue(){const q=queueSummary();$('queueBtn').textContent=q.groups?'Очередь · '+q.groups:'Очередь';$('queueError').hidden=!queueError;$('queueError').textContent=queueError?(queueError.committed?'Очередь уже записана. Обнови страницу.':'Не добавлено в очередь: '+queueError.message+' · черновик не очищен'):'';if(!$('queueDialog').open)return;renderQueueDialog();}
function ingestQueue(rows){queueRows=rows;for(const r of rows.filter(OutboxVault.active))for(const f of r.files){if(assets.has(f.id))continue;const a={id:f.id,name:f.name,file:f.file,kind:f.kind,preview:null,state:f.kind==='document'?'ready':'pending',duration:0};assets.set(f.id,a);metadataQueue=metadataQueue.then(()=>makePreview(a)).catch(fatal)}
 const held=new Set([...draft.attachments,...rows.filter(OutboxVault.active).flatMap(r=>r.files.map(f=>f.id))]);for(const [id,a]of assets){if(!held.has(id)){urlRevoke(a.preview);assets.delete(id)}}
 if(list){const a=list.capture(),f=list.follow;list.messages=list.messages.filter(m=>!m.outboxId).concat(queueMessages());list.sync(a,f,'queue-update');}paintQueue();}
async function refreshQueue(){const rows=await vault.store.readQueue();ingestQueue(rows);return rows;}
async function localSend(){
 if(!list||submitBusy||draft.composing||(!input.value.trim()&&!draft.attachments.length))return;
 if(draft.mode!=='message'){startTask();return}
 if(!queueLoaded||!vault.ready){status('Очередь ещё не восстановлена');return}
 let committed=false;submitBusy=true;queueError=null;closeMenu(false);const focused=document.activeElement===input;
 $('composeBox').inert=true;$('send').disabled=true;$('queueError').hidden=true;
 try{
  vault.changed();await vault.flush();const saved=await vault.store.read();
  if(!saved||(!saved.text.trim()&&!saved.files.length))throw Object.assign(Error('Нет сохранённого черновика'),{name:'DataError'});
  submitToken={intent:saved.intent,revision:saved.revision};vault.restoring=true;clearTimeout(vault.timer);
  status('Сохраняю исходящее в очередь…');const result=await vault.store.enqueue(submitToken.intent,submitToken.revision);committed=true;
  if(window.gate.crashAfterCommit){location.reload();return}
  const latest=await vault.store.read();vault.pending=null;vault.rev=latest.revision;
  if(!result.deduplicated){input.value='';draft.attachments=[];$('tray').replaceChildren();draft.expanded=false;draft.mode='message';draft.task=null;renderTask();}
  else await restoreDraft(latest);
  vault.lastSignature=DraftVault.signature(captureDraft());vault.restoring=false;vault.set('saved');
  await refreshQueue();syncComposer();list.bottom();queueStats.enqueued_here+=result.deduplicated?0:1;cm.local_sends++;
  status('В очереди · не отправлено. Сервер в этом стенде не подключён.');
 }catch(e){queueError=Object.assign(e,{committed});queueStats.commit_failures++;status(committed?'Очередь записана, но её отображение не обновилось. Перезагрузи страницу.':'Ошибка записи очереди. Текст и вложения оставлены в черновике.');}
 finally{vault.restoring=false;submitBusy=false;$('composeBox').inert=false;syncComposer();if(focused&&!window.gate.crashAfterCommit)input.focus({preventScroll:true});paintQueue();}
}
async function retryQueued(id){try{await vault.store.retry(id);queueStats.retried_here++;await refreshQueue();status('Та же запись остаётся в очереди. Сервера нет — отправки не было.')}catch(e){status(e.message)}return queueSummary()}
async function cancelQueued(id,ask=true){if(ask&&!confirm('Отменить это исходящее только в тестовой очереди? Его вложения будут освобождены, если больше не используются.'))return;await vault.store.cancel(id);queueStats.cancelled_here++;await refreshQueue();status('Исходящее отменено локально. Оно не отправлялось.');}
function renderQueueDialog(){const root=$('queueItems');root.replaceChildren();const active=queueRows.filter(OutboxVault.active);$('queueOverview').textContent='Сервер не подключён. Здесь сохраняются исходящие, но ничего не доставляется. '+(active.length?'В очереди: '+active.length+'.':'Очередь пуста.');
 for(const r of active){const box=document.createElement('section');box.className='queueItem';const h=document.createElement('strong');h.textContent='◷ В очереди · не отправлено';const meta=document.createElement('p');meta.textContent='Порядок '+r.first_sequence+' · сообщений: '+r.messages.length+' · файлов: '+r.files.length+' · повторов: '+r.retries;const preview=document.createElement('p');preview.textContent=r.messages.find(m=>m.kind==='text')?.text.slice(0,160)||'Вложения';
 const retry=document.createElement('button');retry.textContent='Повторить';retry.onclick=async()=>{retry.disabled=true;await retryQueued(r.id)};const cancel=document.createElement('button');cancel.textContent='Отменить';cancel.onclick=()=>cancelQueued(r.id).catch(notifyError);box.append(h,meta,preview,retry,cancel);root.append(box)}
}
function showQueue(){closeMenu(false);$('queueDialog').showModal();renderQueueDialog();}
async function verifyQueue(){try{await vault.flush();const first=await OutboxVault.queueFingerprint(queueRows),stored=await vault.store.readQueue(),second=await OutboxVault.queueFingerprint(stored);const pass=JSON.stringify(first)===JSON.stringify(second);queueAudit={pass,groups:first.length,files:stored.filter(OutboxVault.active).reduce((n,r)=>n+r.files.length,0),total_bytes:stored.filter(OutboxVault.active).reduce((n,r)=>n+r.files.reduce((a,f)=>a+f.size,0),0),kind:'CURRENT_QUEUE_VS_FRESH_DB',checkedAt:new Date().toISOString()};status(pass?'Очередь: текст, порядок и байты совпали':'Очередь: сверка не пройдена');$('queueNote').textContent=pass?'Сверка очереди пройдена':'Сверка не пройдена';return queueAudit;}catch(e){queueAudit={pass:false,error:e.name};notifyError(e);throw e;}}
async function reloadQueue(){
 vault.changed();await vault.flush();const rows=await vault.store.readQueue();const proof=await OutboxVault.queueFingerprint(rows);await vault.store.transaction(['proofs'],'readwrite',tx=>tx.objectStore('proofs').put({id:'queue-checkpoint',value:proof,bootId:vault.bootId,at:new Date().toISOString()}));location.reload();
}
async function verifyQueueCheckpoint(){const proof=await vault.store.transaction(['proofs'],'readonly',(tx,done)=>{const q=tx.objectStore('proofs').get('queue-checkpoint');q.onsuccess=()=>done(q.result)});if(proof&&proof.bootId!==vault.bootId){const actual=await OutboxVault.queueFingerprint(queueRows);queueReloadCheck={pass:JSON.stringify(actual)===JSON.stringify(proof.value),groups:actual.length,kind:'ACTUAL_NEW_PAGE_CHECKPOINT',checkedAt:new Date().toISOString()};await vault.store.transaction(['proofs'],'readwrite',tx=>tx.objectStore('proofs').delete('queue-checkpoint'));if(!queueReloadCheck.pass)status('Контроль очереди после обновления: несовпадение');}}
async function runQueueTests(){if(queueTestsBusy||submitBusy)return publicSnapshot();queueTestsBusy=true;$('auto').disabled=true;const before=DraftVault.signature(captureDraft()),beforeQ=JSON.stringify(queueSummary().entries);status('Проверяю отдельную временную базу, твоя очередь не меняется');try{queueTests=await OutboxVault.tests();queueTests.results.push({name:'Автотест не меняет черновик и пользовательскую очередь',pass:before===DraftVault.signature(captureDraft())&&beforeQ===JSON.stringify(queueSummary().entries),measured:true});queueTests.overall=queueTests.results.every(r=>r.pass)?'PASS':'FAIL';queueTests.summary={checks:queueTests.results.length,passed:queueTests.results.filter(x=>x.pass).length};status('ОЧЕРЕДЬ: '+queueTests.overall+' · реальная доставка не проверялась')}catch(e){queueTests={overall:'FAIL',results:[{name:'Выполнение теста',pass:false,measured:e.name}],summary:{checks:1,passed:0}}}finally{queueTestsBusy=false;$('auto').disabled=false}return publicSnapshot();}
