/* Vision Talk — Telegram-first attachment hub, v14 */
(()=>{
'use strict';
const V='attachments-v14';
const originalOpenConversation=typeof openConversation==='function'?openConversation:null;
const originalRenderDialogs=typeof renderDialogs==='function'?renderDialogs:null;
const state={tab:'gallery',files:[],urls:[]};
const i={
 close:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg>`,
 camera:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14.5 6 13 4h-2L9.5 6H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-4.5Z"/><circle cx="12" cy="12.5" r="3.5"/></svg>`,
 photo:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m21 15-5-5L5 20"/></svg>`,
 file:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/></svg>`,
 pin:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>`,
 contact:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>`,
 scan:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4M7 12h10"/></svg>`,
 live:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="2"/><path d="M8.5 8.5a5 5 0 0 0 0 7M15.5 8.5a5 5 0 0 1 0 7M5.5 5.5a9 9 0 0 0 0 13M18.5 5.5a9 9 0 0 1 0 13"/></svg>`
};
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function closeHub(){document.getElementById('attachmentBackdrop')?.remove()}
function clearFiles(){for(const u of state.urls)URL.revokeObjectURL(u);state.files.length=0;state.urls.length=0;state.tab='gallery'}
function size(n){if(n<1024)return n+' Б';if(n<1048576)return(n/1024).toFixed(1)+' КБ';return(n/1048576).toFixed(1)+' МБ'}
function picker(id){document.getElementById(id)?.click()}
function ensurePickers(){const shell=document.querySelector('.chatShell');if(!shell||document.getElementById('galleryPickerV14'))return;const defs=[['galleryPickerV14','image/*,video/*',true,''],['cameraPickerV14','image/*,video/*',false,'environment'],['documentPickerV14','.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.rtf,.zip,.rar,.7z',true,''],['scanPickerV14','image/*',false,'environment'],['filePickerV14','',true,''],['contactPickerV14','.vcf,text/vcard,text/x-vcard',false,'']];for(const[d,accept,multiple,capture]of defs){const x=document.createElement('input');x.id=d;x.type='file';x.hidden=true;if(accept)x.accept=accept;if(multiple)x.multiple=true;if(capture)x.setAttribute('capture',capture);shell.appendChild(x)}
 document.getElementById('galleryPickerV14').onchange=x=>picked(x.target.files,'gallery',x.target);
 document.getElementById('cameraPickerV14').onchange=x=>picked(x.target.files,'camera',x.target);
 document.getElementById('documentPickerV14').onchange=x=>picked(x.target.files,'document',x.target);
 document.getElementById('scanPickerV14').onchange=x=>picked(x.target.files,'scan',x.target);
 document.getElementById('filePickerV14').onchange=x=>picked(x.target.files,'file',x.target);
 document.getElementById('contactPickerV14').onchange=contactFile;
}
function picked(list,source,input){for(const f of Array.from(list||[])){const key=[f.name,f.size,f.lastModified].join(':');if(state.files.some(v=>v.key===key))continue;let url='';if(/^image\//.test(f.type)||/^video\//.test(f.type)){url=URL.createObjectURL(f);state.urls.push(url)}state.files.push({key,file:f,url,source})}if(input)input.value='';render();if(state.files.length)showStatus(`Выбрано файлов: ${state.files.length}`,'good')}
async function contactFile(x){const f=x.target.files?.[0];x.target.value='';if(!f)return;try{const t=await f.text(),name=(t.match(/^FN:(.+)$/mi)?.[1]||f.name).trim(),tel=(t.match(/^TEL[^:]*:(.+)$/mi)?.[1]||'').trim(),mail=(t.match(/^EMAIL[^:]*:(.+)$/mi)?.[1]||'').trim();closeHub();await sendPayload(['👤 '+name,tel,mail].filter(Boolean).join('\n'))}catch{showStatus('Не удалось прочитать контакт','bad')}}
function tab(id,label,icon){return`<button class="attachmentTab ${state.tab===id?'active':''}" data-tab="${id}">${icon}<span>${label}</span></button>`}
function fileList(filter){const a=state.files.filter(filter||(()=>true));return a.length?`<div class="selectedFiles">${a.map(v=>`<div class="selectedFile"><div class="selectedFileIcon">${/^image\//.test(v.file.type)?i.photo:/^video\//.test(v.file.type)?i.camera:i.file}</div><div><div class="selectedFileName">${e(v.file.name)}</div><div class="selectedFileMeta">${size(v.file.size)}</div></div></div>`).join('')}</div>`:''}
function gallery(){const a=state.files.filter(v=>/^image\//.test(v.file.type)||/^video\//.test(v.file.type)).slice(0,8),thumb=a.map(v=>`<button class="mediaThumb">${/^video\//.test(v.file.type)?`<video src="${v.url}" muted playsinline></video><span class="mediaType">Видео</span>`:`<img src="${v.url}" alt="">`}<span class="mediaCheck">✓</span></button>`).join(''),empty=Math.max(0,3-a.length);return`<div class="galleryLead"><button id="cameraTileV14" class="cameraTile">${i.camera}<span>Камера</span></button><div class="gallerySide"><button id="galleryOpenV14" class="galleryOpen">${i.photo}<span>Открыть галерею</span></button>${thumb}${Array.from({length:empty},()=>'<button class="galleryPlaceholder" data-gallery-v14></button>').join('')}</div></div><div class="attachmentHint">В веб‑версии iPhone не разрешает заранее читать всю фотоплёнку. Тап открывает системную галерею; выбранные фото и видео сразу появляются здесь.</div>`}
function panel(){switch(state.tab){case'gallery':return gallery();case'location':return`<div class="attachmentPanel"><button id="locationNowV14" class="panelAction">${i.pin}<span><strong>Отправить геопозицию</strong><small>Текущая точка по GPS</small></span></button><button id="locationLiveV14" class="panelAction">${i.live}<span><strong>Транслировать геопозицию</strong><small>Обновление в реальном времени — следующий серверный блок</small></span></button></div>`;case'contact':return`<div class="attachmentPanel"><button id="contactV14" class="panelHero">${i.contact}<h3>Контакт</h3><p>Выберите контакт из системного списка либо карточку vCard.</p></button></div>`;case'document':return`<div class="attachmentPanel"><button id="documentV14" class="panelAction">${i.file}<span><strong>Выбрать документ</strong><small>PDF, Word, Excel, презентации и архивы</small></span></button><button id="documentScanV14" class="panelAction">${i.scan}<span><strong>Сканировать документ</strong><small>Открыть камеру для скана</small></span></button>${fileList(v=>v.source==='document'||v.source==='scan')}</div>`;case'scan':return`<div class="attachmentPanel"><button id="scanV14" class="panelHero">${i.scan}<h3>Сканер документов</h3><p>Откройте камеру и снимите документ. Автокадрирование и PDF — отдельный модуль.</p></button>${fileList(v=>v.source==='scan')}</div>`;case'file':return`<div class="attachmentPanel"><button id="fileV14" class="panelHero">${i.file}<h3>Файл</h3><p>Выберите любой файл из приложения «Файлы».</p></button>${fileList(v=>v.source==='file')}</div>`;default:return gallery()}}
function title(){return state.tab==='gallery'?'Недавние':({location:'Геопозиция',contact:'Контакты',document:'Документы',scan:'Сканер',file:'Файлы'}[state.tab]||'Вложения')}
function render(){const b=document.getElementById('attachmentBodyV14'),t=document.getElementById('attachmentTitleV14');if(!b)return;if(t)t.innerHTML=`${title()}<span class="sheetSubtitle">${state.files.length?'Выбрано: '+state.files.length:V}</span>`;b.innerHTML=panel();document.querySelectorAll('.attachmentTab').forEach(x=>x.classList.toggle('active',x.dataset.tab===state.tab));bindPanel()}
function bindPanel(){document.getElementById('cameraTileV14')?.addEventListener('click',()=>picker('cameraPickerV14'));document.getElementById('galleryOpenV14')?.addEventListener('click',()=>picker('galleryPickerV14'));document.querySelectorAll('[data-gallery-v14]').forEach(x=>x.addEventListener('click',()=>picker('galleryPickerV14')));document.getElementById('documentV14')?.addEventListener('click',()=>picker('documentPickerV14'));document.getElementById('documentScanV14')?.addEventListener('click',()=>picker('scanPickerV14'));document.getElementById('scanV14')?.addEventListener('click',()=>picker('scanPickerV14'));document.getElementById('fileV14')?.addEventListener('click',()=>picker('filePickerV14'));document.getElementById('locationNowV14')?.addEventListener('click',locationNow);document.getElementById('locationLiveV14')?.addEventListener('click',()=>showStatus('Live‑геопозицию подключаем отдельным серверным блоком'));document.getElementById('contactV14')?.addEventListener('click',contact)}
async function locationNow(){if(!navigator.geolocation)return showStatus('Геолокация недоступна в этом браузере','bad');showStatus('Определяю геопозицию…');navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude.toFixed(6),lng=p.coords.longitude.toFixed(6);closeHub();await sendPayload(`📍 Геопозиция\nhttps://maps.google.com/?q=${lat},${lng}`)},x=>showStatus(x.message||'Не удалось получить геопозицию','bad'),{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
async function contact(){try{if(navigator.contacts?.select){const r=await navigator.contacts.select(['name','tel','email'],{multiple:false}),c=r?.[0];if(!c)return;closeHub();await sendPayload(['👤 '+(c.name?.[0]||'Контакт'),c.tel?.[0]||'',c.email?.[0]||''].filter(Boolean).join('\n'));return}}catch(x){console.warn(x)}picker('contactPickerV14')}
async function sendPayload(body){if(!body||!currentConversation)return;const input=document.getElementById('message'),id=globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();closeHub();const m={conversation_id:currentConversation.id,client_message_id:id,body,created_at:Date.now()};enqueue(m);appendPending(m,true);if(!navigator.onLine){showStatus('Нет сети · сообщение сохранено','bad');return}const{data,error}=await sb.rpc('send_message',{p_conversation_id:m.conversation_id,p_client_message_id:m.client_message_id,p_type:'text',p_body:m.body,p_attachment_path:null});if(error){showStatus('Отправка отложена · сохранено в очереди','bad');return}if(data)appendMessages([data],true);dequeue(m.client_message_id);await syncNewMessages(currentConversation,true);await syncPeerRead();input?.focus({preventScroll:true})}
function openHub(){if(document.getElementById('attachmentBackdrop')){closeHub();return}const shell=document.querySelector('.chatShell');if(!shell)return;ensurePickers();document.getElementById('message')?.blur();state.tab='gallery';const d=document.createElement('div');d.id='attachmentBackdrop';d.className='attachmentBackdrop';d.innerHTML=`<section class="attachmentSheet" role="dialog" aria-modal="true"><header class="attachmentHeader"><button id="attachmentCloseV14" class="iconBtn sheetClose" aria-label="Закрыть">${i.close}</button><div id="attachmentTitleV14" class="sheetTitle"></div><span class="sheetSpacer"></span></header><main id="attachmentBodyV14" class="attachmentBody"></main><nav class="attachmentNav">${tab('gallery','Галерея',i.photo)}${tab('location','Геопозиция',i.pin)}${tab('contact','Контакт',i.contact)}${tab('document','Документ',i.file)}${tab('scan','Сканер',i.scan)}${tab('file','Файл',i.file)}</nav></section>`;shell.appendChild(d);d.addEventListener('click',x=>{if(x.target===d)closeHub()});d.querySelector('.attachmentSheet').addEventListener('click',x=>x.stopPropagation());document.getElementById('attachmentCloseV14').onclick=closeHub;d.querySelectorAll('.attachmentTab').forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;render()});render()}
function install(){const shell=document.querySelector('.chatShell');if(!shell)return;ensurePickers();const a=document.getElementById('attach'),cam=document.getElementById('camera'),msg=document.getElementById('messages'),input=document.getElementById('message');if(a)a.onclick=openHub;if(cam)cam.onclick=()=>picker('cameraPickerV14');if(msg&&!msg.dataset.v14close){msg.dataset.v14close='1';msg.addEventListener('pointerdown',()=>{if(document.getElementById('attachmentBackdrop'))closeHub()},{passive:true})}if(input&&!input.dataset.v14close){input.dataset.v14close='1';input.addEventListener('focus',closeHub)}document.querySelector('.chatPresence')?.replaceChildren(document.createTextNode('Vision Talk · '+V))}
try{openTools=openHub;closeTools=closeHub}catch{}
if(originalOpenConversation){openConversation=async function(...a){const r=await originalOpenConversation(...a);install();return r}}
if(originalRenderDialogs){renderDialogs=async function(...a){closeHub();clearFiles();const r=await originalRenderDialogs(...a);document.querySelectorAll('.small').forEach(x=>{if(x.textContent.includes('Vision talk'))x.textContent='Vision talk · '+V});return r}}
function refreshVersion(){document.querySelectorAll('.small').forEach(x=>{if(x.textContent.includes('Vision talk'))x.textContent='Vision talk · '+V});if(document.querySelector('.chatShell'))install()}
setTimeout(refreshVersion,0);
document.addEventListener('DOMContentLoaded',()=>setTimeout(refreshVersion,0));
})();