from pathlib import Path
import json,hashlib,collections,re,xml.etree.ElementTree as ET,subprocess,shutil
W=Path('/Users/artem/Documents/ChatGPT/Pablicus');R=W/'design-handoff-20260912';P=R/'docs/pablicus/design/handoff/2026-09-12';M=P/'00_manifest'
meta=json.loads((M/'_INVENTORY_WORK.json').read_text())
def add(name,b,purpose):
 p=M/name;p.write_bytes(b if isinstance(b,bytes) else b.encode());rel=str(p.relative_to(P))
 meta[rel]=dict(stage='HANDOFF',status='DOCUMENTATION_ONLY',purpose=purpose,provenance='Created solely for this inventory handoff',licence_status='Project handoff documentation',is_actual_visual=False,visual_or_description='DESCRIPTION_OR_INVENTORY',created_in_design_contour=True,preexisting_before_handoff=False,tags=[])
ctx={'kind':'NON_VERBATIM_CONTEXT_EXPORT','new_design_created':False,'source':'Earlier D1 conversation/tool calls; this is a structured record, not the original verbatim tool log','image_generation_tool':'image_gen.imagegen','reference_supplied_to_each_call':'09_references/RonDesignLab/my-notes-ui.jpg','reference_policy':'Observed mobile collage supplied for principles only; prompts prohibited copying brand, logo, palette, fonts, layout and glyphs','requested_board_dimensions':'1800x1200 with three mobile app-content frames at390x844 logical aspect; requested dimensions not a verified output dimension','common_fixture_date':'2026-09-12','concepts':[{'direction':'A / ORBIT','output_original':'exec-d3392557-09a2-43f1-8673-2b59b1d4316d.png','prompt_context':'Suspended object, porcelain/evergreen surfaces, limited translucent controls, opaque work content; same Север conversation → expanded scenario → result.'},{'direction':'B / FOLIO','output_original':'exec-f589e838-f7e6-4049-98ae-a4dda0373e19.png','prompt_context':'Opaque editorial surface, spine and margins, no glass, document insert→workspace; same Север scenario. Generated board contains serif character beyond initial sans instruction; subsequent report distinguishes interim display serif.'},{'direction':'C / RELAY','output_original':'exec-08a5c754-9d85-4067-b3bd-99aead6ff6cd.png','prompt_context':'Opaque precise modules, phase rails and ports, offwhite/navy/blue, explicit approval; same Север scenario.'}],'earlier_observed_limitations':['No completed browser visual QA: CUA timed out and isolated Opera headless screenshot did not materialize.','No real iPhone/VoiceOver validation.','Hero images approximate labels/fonts/targets; contract and static HTML were separately authored.','No recorded motion video, Figma source, PDF or production implementation.','No full verbatim generation tool-log file existed locally. This record exports known context without inventing missing requests.'],'owner_gate':'Direction selection pending; no new stage authorised by this packaging task'}
add('GENERATION_CONTEXT_EXPORT.json',json.dumps(ctx,ensure_ascii=False,indent=2),'Structured export of previously context-only generation provenance; explicitly non-verbatim, no new design')
add('finalize_handoff.py',Path('/tmp/pablicus_handoff_finalize.py').read_bytes(),'Inventory finalizer and content checks; not a design generator')
# Only real visual files appear; asset binaries and source-only HTML are not screen specimens.
visuals=[(p,m) for p,m in sorted(meta.items()) if m['is_actual_visual']]
s=['# Visual index — only existing files','', 'Frozen prior design work. This index creates no visual. Current/proposed/reference is an evidence classification, not owner acceptance. All paths are relative to this index.','', '| File | What / screen or component | Current / proposed / reference | Original / interim / third-party | Stage | Independent review focus |','|---|---|---|---|---|---|']
for path,m in visuals:
 if m['status']=='REFERENCE':phase='reference';auth='third-party reference';focus='Inspect principle only; do not attribute this UI/logo to Pablicus.'
 elif m['status']=='EXISTING_RUNTIME':phase='current legacy capture';auth='existing Pablicus runtime, captured by assistant';focus='Legacy login evidence only; NOT_A_DESIGN_BASELINE.'
 else:
  phase='proposed';auth='generated study' if m['status']=='GENERATED_STUDY' else 'original D1 study'
  focus='Evaluate actual visual hierarchy and relationship of conversation/object/result; labels/fonts are approximate.' if path.endswith('.png') else 'Inspect draft geometry in component context; not final icon system.' if '/icons/' in path else 'Inspect static state progression; not a live motion prototype.' if '/motion/' in path else 'Open whole local gallery with fonts/visuals; inspect embedded specimens and separate them from implemented behavior.'
 if 'DUPLICATE_VISUAL_BYTES' in m['tags']:focus='Byte-identical original filename alias of a named hero board; not another direction.'
 s.append('| ['+Path(path).name+'](../'+path+') | '+m['purpose'].replace('|','/')+' | '+phase+' | '+auth+' | '+m['stage']+' | '+focus+' |')
s += ['','## Explicit absences','No standalone78 mobile images: the78 states live in one HTML file. No Figma source, PDF, native screen prototype, rendered motion video,285 final icon glyphs, original Pablicus font binaries, full interactive runtime, full visual state catalogue for every future flow, or final token library exists. Token values/interaction and accessibility requirements in Markdown and demo CSS are proposals, not approved production tokens.','', 'The index counts3 original-filename duplicates in addition to3 named generated boards. These are not6 concepts. Font binaries and third-party webpage source HTML are not visual screen results.']
add('VISUAL_INDEX.md','\n'.join(s)+'\n','Index containing only real existing visual files, their provenance and inspection targets')
# Validate byte-for-byte preservation, source snapshots and offline gallery dependencies.
mapping=json.loads((M/'ORIGINAL_FILE_MAPPING.json').read_text());bad=[]
for row in mapping:
 if hashlib.sha256((P/row['package_path']).read_bytes()).hexdigest()!=row['sha256']:bad.append(row['package_path'])
assert not bad,bad
xmls=list(P.rglob('*.svg'))
for x in xmls:ET.parse(x)
gallery=P/'10_prototypes/D1/index.html';txt=gallery.read_text();missing=[]
for link in re.findall(r'(?:src|href)="([^"#]+)"',txt)+re.findall(r"url\('([^']+)'\)",txt):
 if not link.startswith(('https:','http:','data:')) and not (gallery.parent/link).exists():missing.append(link)
assert not missing,missing
checks={'scope':'File/integrity handoff checks only; not a new design audit or browser acceptance','copied_original_files':len(mapping),'byte_changed_original_files':bad,'source_snapshot_files':len([x for x in meta if '/source_snapshot/' in x]),'svg_xml_valid_count':len(xmls),'gallery_dependency_missing':missing,'gallery_mobile_ids':{t:all(f'id="{t}-{i:02}"' in txt for i in range(1,27)) for t in 'ABC'},'new_visual_files_created_during_handoff':0,'runtime_application_modified':False,'historical_source_copies_under_docs_only':True,'browser_visual_verification':'Not performed in this handoff; previous attempts failed, retained as limitation','deployment':'NOT_RUN','manifests_self_checksum_exclusion':'Only the two self-describing manifest files; their exact hashes are supplied in final response and files are pinned by Git commit'}
add('HANDOFF_CHECKS.json',json.dumps(checks,ensure_ascii=False,indent=2),'Actual integrity check results for copied files, SVG and gallery dependencies')
# Move scratch metadata outside package; it is implementation scratch, not a design deliverable.
shutil.copy2(M/'_INVENTORY_WORK.json','/tmp/pablicus_handoff_inventory_work.json');(M/'_INVENTORY_WORK.json').unlink()
entries=[]
for path,m in sorted(meta.items()):
 p=P/path;b=p.read_bytes();entries.append(dict(relative_path=path,filename=p.name,type=p.suffix.lstrip('.') or 'file',sha256=hashlib.sha256(b).hexdigest(),size_bytes=len(b),**m))
st=collections.Counter(e['status'] for e in entries);vc=sum(e['is_actual_visual'] for e in entries)
summary={'FILES_TOTAL':len(entries)+2,'VISUAL_FILES_TOTAL':vc,'UNIQUE_VISUAL_SHA256_TOTAL':len({e['sha256'] for e in entries if e['is_actual_visual']}),'DOCUMENTATION_ONLY_TOTAL':st['DOCUMENTATION_ONLY']+2,'ORIGINAL_DESIGN_FILES_TOTAL':st['ORIGINAL_PABLICUS_DESIGN'],'REFERENCE_FILES_TOTAL':st['REFERENCE'],'GENERATED_STUDY_FILES_TOTAL':st['GENERATED_STUDY'],'INTERIM_FILES_TOTAL':st['INTERIM'],'EXISTING_RUNTIME_FILES_TOTAL':st['EXISTING_RUNTIME']}
out={'package_root':'docs/pablicus/design/handoff/2026-09-12/','repository':'matveyryabokon30-crypto/vision-talk','branch':'design/pablicus-design-handoff-20260912','BASE_SHA':'883003ebe9ae25d3c97b657234d0b6cab72414dd','historical_design_source_sha':'d791adc19aade1015f4ba34cf4beb5ce2069c93f','stage':'HANDOFF_OF_EXISTING_D0_D1','new_design_created':False,'runtime_changed':False,'deployed':False,'summary':summary,'counting':'Physical package files; embedded HTML frames and ZIP members are not extra physical files; includes3 explicit duplicate original PNGs. Original design means study authorship, not approval.','self_describing_manifest_files':[{'relative_path':'00_manifest/DESIGN_HANDOFF_MANIFEST.'+ext,'type':ext,'stage':'HANDOFF','status':'DOCUMENTATION_ONLY','created_in_design_contour':True,'is_actual_visual':False,'provenance':'This handoff inventory','licence_status':'Project documentation','purpose':'Self-describing file manifest','sha256':'SUPPLIED_IN_FINAL_RESPONSE_AND_PINNED_BY_GIT_COMMIT; excluded from own checksum recursion'} for ext in ['md','json']],'files':entries}
(M/'DESIGN_HANDOFF_MANIFEST.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
lines=['# DESIGN HANDOFF MANIFEST','', 'Repository: matveyryabokon30-crypto/vision-talk','Branch: design/pablicus-design-handoff-20260912','BASE_SHA:883003ebe9ae25d3c97b657234d0b6cab72414dd','Historical design-source SHA:d791adc19aade1015f4ba34cf4beb5ce2069c93f','', 'Existing work frozen without visual changes. Runtime/deploy: NO. Counts include2 manifest files; only this self-describing pair is excluded from its checksum inventory. Exact hashes are supplied in final response and both files are pinned by Git commit. All payload bytes below have exact SHA-256. Manifest pair: HANDOFF / DOCUMENTATION_ONLY / authored during handoff / not visual.','', '## Counts','', *[f'- {k}: {v}' for k,v in summary.items()], '', '## Every payload file', '', '| Relative path / filename | Type / bytes / SHA-256 | Stage / status | Purpose | Provenance / source | Licence | Actual visual? / created in design contour? |','|---|---|---|---|---|---|---|']
for e in entries:
 vals=[f"[{e['relative_path']}](../{e['relative_path']})",f"{e['type']} / {e['size_bytes']} / `{e['sha256']}`",e['stage']+' / '+e['status']+(' / '+','.join(e['tags']) if e['tags'] else ''),e['purpose'],e['provenance'],e['licence_status'],str(e['is_actual_visual'])+' / '+str(e['created_in_design_contour'])]
 lines.append('| '+' | '.join(v.replace('|','/').replace('\n',' ') for v in vals)+' |')
(M/'DESIGN_HANDOFF_MANIFEST.md').write_text('\n'.join(lines)+'\n')
actual={str(p.relative_to(P)) for p in P.rglob('*') if p.is_file()};expected={e['relative_path'] for e in entries}|{'00_manifest/DESIGN_HANDOFF_MANIFEST.json','00_manifest/DESIGN_HANDOFF_MANIFEST.md'};assert actual==expected,(actual-expected,expected-actual)
print(json.dumps(summary,indent=2))
print('MANIFEST SHA256:')
for ext in ['md','json']:
 p=M/('DESIGN_HANDOFF_MANIFEST.'+ext);print(p.name,p.stat().st_size,hashlib.sha256(p.read_bytes()).hexdigest())
