from pathlib import Path
import argparse, json, subprocess, tempfile, shutil, threading, http.server, socketserver, time
from playwright.sync_api import sync_playwright

ap=argparse.ArgumentParser();ap.add_argument('--source-root',type=Path,default=Path.cwd());ap.add_argument('--browser',default=shutil.which('chromium'));ap.add_argument('--output-dir',type=Path,default=Path('block01-results'));ap.add_argument('--entrypoint-url',default='');a=ap.parse_args();root=a.source_root.resolve();site=root/'pablicus';out=a.output_dir.resolve();out.mkdir(parents=True,exist_ok=True)
results={}
def record(tid, ok, detail): results[tid]={'status':'PASS' if ok else 'FAIL','detail':detail}; assert ok, f'{tid}: {detail}'
FIX='''<!doctype html><body><div id="home"><header><span id="brandTitle">Чаты</span></header><section id="workspace"><input id="searchChats"><div id="chatFilters"></div><button id="newChat"></button><div id="screenContent"></div></section><nav id="mainNav"><button data-page="chats" class="selected">Чаты</button><button data-page="feed">Лента</button><button data-page="tasks">Дела</button><button data-page="profile">Профиль</button></nav></div><div id="app"><button id="conversationTab" aria-selected="true"></button><button id="canvasTab" aria-selected="false"></button><section id="chatCanvasPanel"></section><footer id="composer"></footer></div><div id="toast"></div></body>'''
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=a.browser,headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 # T01/T02/T03 real chat-list-view
 for count in (3,100):
  pg=b.new_page();pg.set_content(FIX);pg.add_script_tag(path=str(site/'chat-list-view.js'));d=pg.evaluate('''n=>{const c=document.querySelector('#screenContent'),items=[];for(let i=0;i<n;i++){let x=document.createElement('section');x.dataset.conversationId='c'+i;c.append(x);items.push({id:'c'+i})}let mo=0;const o=new MutationObserver(r=>mo+=r.length);o.observe(c,{childList:true});const f=new Set(['c1']);let r1=PablicusChatListView.reconcile(c,items,f);return new Promise(res=>setTimeout(()=>{let before=mo;setTimeout(()=>{let r2=PablicusChatListView.reconcile(c,items,f);res({r1:r1.changed,r2:r2.changed,delta:mo-before,ids:[...c.children].map(x=>x.dataset.conversationId)})},5100)},50))}''',count)
  record('B1-T01-'+str(count), d['delta']==0 and d['r2']==False, d);pg.close()
 pg=b.new_page();pg.set_content(FIX);pg.add_script_tag(path=str(site/'chat-list-view.js'));d=pg.evaluate('''()=>{const c=document.querySelector('#screenContent'),items=[0,1,2].map(i=>({id:'c'+i}));for(const x of items){let n=document.createElement('section');n.dataset.conversationId=x.id;c.append(n)}c.hidden=true;let mo=0;new MutationObserver(r=>mo+=r.length).observe(c,{childList:true});PablicusChatListView.reconcile(c,items,new Set(['c1']));return new Promise(r=>setTimeout(()=>{let before=mo;setTimeout(()=>r({delta:mo-before}),5100)},50))}''');record('B1-T02',d['delta']==0,d);pg.close()
 pg=b.new_page();pg.set_content(FIX);pg.add_script_tag(path=str(site/'chat-list-view.js'));d=pg.evaluate('''()=>{const c=document.querySelector('#screenContent'),items=[0,1,2].map(i=>({id:'c'+i}));for(const x of items){let n=document.createElement('section');n.dataset.conversationId=x.id;n._identity=Math.random();c.append(n)}const ids0=[...c.children].map(n=>n._identity);let a=PablicusChatListView.reconcile(c,items,new Set(['c2']));let ids1=[...c.children].map(n=>n.dataset.conversationId),ident=[...c.children].map(n=>n._identity).sort();let b=PablicusChatListView.reconcile(c,items,new Set(['c2']));return{a:a.changed,b:b.changed,ids1,identity:JSON.stringify(ident)===JSON.stringify(ids0.sort()),count:c.children.length}}''');record('B1-T03',d['a'] and not d['b'] and d['ids1'][0]=='c2' and d['identity'] and d['count']==3,d);pg.close()
 # T04 lifecycle controller 50 cycles
 pg=b.new_page();pg.set_content(FIX);pg.add_script_tag(path=str(site/'app-controller.js'));d=pg.evaluate('''async()=>{let active=0,actions=0;PablicusController.register('home',async()=>{active++;let h=()=>actions++;document.body.addEventListener('x',h);return()=>{document.body.removeEventListener('x',h);active--}});for(let i=0;i<50;i++){await PablicusController.navigate({section:'chats',screen:'home'});await PablicusController.navigate({section:'profile',screen:'home'})}document.body.dispatchEvent(new Event('x'));return{active,actions}}''');record('B1-T04',d=={'active':1,'actions':1},d);pg.close()
 # T05 navigation state/title projection model + bot ID
 pg=b.new_page();pg.set_content(FIX);pg.add_script_tag(path=str(site/'app-controller.js'));d=pg.evaluate('''async()=>{let seen=[];for(const k of ['home','bots','factory','scenario','conversation'])PablicusController.register(k,async({state})=>{seen.push([state.section,state.screen,state.resourceId,state.conversationId,state.canvas]);return()=>{}});for(const x of [{section:'chats',screen:'home'},{section:'feed',screen:'home'},{section:'tasks',screen:'home'},{section:'bots',screen:'bots'},{section:'bots',screen:'factory'},{section:'bots',screen:'scenario',resourceId:'bot-B'},{section:'profile',screen:'home'},{section:'chats',screen:'home'},{section:'chats',screen:'conversation',conversationId:'c1'},{section:'chats',screen:'conversation',conversationId:'c1',canvas:true},{section:'chats',screen:'conversation',conversationId:'c1',canvas:false}])await PablicusController.navigate(x);return{seen,state:PablicusController.state()}}''');record('B1-T05',d['seen'][5][2]=='bot-B' and d['seen'][6][2] is None and d['state']['conversationId']=='c1' and d['state']['resourceId'] is None and d['state']['canvas']==False,d);pg.close()
 # T06 stale async
 pg=b.new_page();pg.set_content(FIX);pg.add_script_tag(path=str(site/'app-controller.js'));d=pg.evaluate('''async()=>{let applied=[];let release;PablicusController.register('A',async({isCurrent})=>{await new Promise(r=>release=r);if(isCurrent())applied.push('A');return()=>{}});PablicusController.register('B',async({isCurrent})=>{if(isCurrent())applied.push('B');return()=>{}});let pa=PablicusController.navigate({screen:'A',resourceId:'a'});await new Promise(r=>setTimeout(r,10));await PablicusController.navigate({screen:'B',resourceId:'b'});release();await pa;let release2;PablicusController.register('C',async({isCurrent})=>{await new Promise(r=>release2=r);if(isCurrent())applied.push('C');return()=>{}});let pc=PablicusController.navigate({screen:'C',resourceId:'c'});await new Promise(r=>setTimeout(r,10));PablicusController.sessionChanged();release2();await pc;return{applied,state:PablicusController.state()}}''');record('B1-T06',d['applied']==['B'],d);pg.close()
 # T08 real chat-canvas project disclosure/edit
 pg=b.new_page();pg.set_content('<div id="host"></div>');pg.evaluate('''()=>{window.PablicusWorkspaceEditor={create:({host})=>({isDirty:()=>false,snapshot:()=>({content:{v:1,blocks:[]},files:[],errors:[]}),setContent:()=>{},focus:()=>{},stopRecording:async()=>{},validate:()=>({ok:true}),clear:()=>{},destroy:()=>{}})}}''');pg.add_script_tag(path=str(site/'chat-canvas.js'));d=pg.evaluate('''async()=>{const api=PablicusChatCanvas.create({host:document.querySelector('#host'),getContext:()=>({userId:'u',conversationId:'c',epoch:1}),load:async()=>({conversation_id:'c',canvas:{content:{v:1,blocks:[{id:'t',type:'text',text:'Saved'}]},body:'Saved',revision:1},tasks:[],participants:[]}),savePlan:async()=>({conversation_id:'c',canvas:{content:{v:1,blocks:[]},revision:2},tasks:[],participants:[]})});await api.open();let card=document.querySelector('.pccProjectCard'),edit=document.querySelector('.pccPlanEdit');card.click();let read=!document.querySelector('.pccProjectView').hidden,editing1=!document.querySelector('.pccPlanEditor').hidden;edit.click();let editing2=!document.querySelector('.pccPlanEditor').hidden;return{read,editing1,editing2}}''');record('B1-T08',d=={'read':True,'editing1':False,'editing2':True},d);pg.close()
 # T09 storage/background survives navigation
 pg=b.new_page();pg.set_content(FIX);pg.evaluate("""()=>{let store={};Object.defineProperty(window,'localStorage',{configurable:true,value:{setItem:(k,v)=>store[k]=String(v),getItem:k=>Object.prototype.hasOwnProperty.call(store,k)?store[k]:null,removeItem:k=>delete store[k],clear:()=>{store={}}}})}""");pg.add_script_tag(path=str(site/'app-controller.js'));d=pg.evaluate('''async()=>{localStorage.setItem('legacy-draft','x');let ticks=0;let timer=setInterval(()=>ticks++,5);PablicusController.register('home',async()=>()=>{});PablicusController.register('conversation',async()=>()=>{});await PablicusController.navigate({screen:'home'});await PablicusController.navigate({screen:'conversation',conversationId:'c'});await new Promise(r=>setTimeout(r,30));clearInterval(timer);return{draft:localStorage.getItem('legacy-draft'),ticks}}''');record('B1-T09',d['draft']=='x' and d['ticks']>0,d);pg.close()
 b.close()
# T07 source assertions
app=(site/'app.js').read_text();bn=(site/'bots-nav.js').read_text();br=(site/'bot-scenario-bridge.js').read_text();record('B1-T07', app.count("persistSession:true")==1 and app.count("persistSession:false")==2 and 'supabase.createClient' not in bn and 'supabase.createClient' not in br and 'getServices()' in bn and 'getServices()' in br, {'bots_duplicate_client': 'supabase.createClient' in bn,'bridge_duplicate_client':'supabase.createClient' in br})
# T10 structural integrated entrypoint + syntax
idx=(site/'index.html').read_text();needed=['app-controller.js','chat-list-view.js'];syntax=[]
for f in ['app-controller.js','chat-list-view.js','app.js','bots.js','bots-nav.js','bot-scenario-bridge.js','ux-refinement.js','public-hotfix-v8.js']:
 r=subprocess.run(['node','--check',str(site/f)],capture_output=True,text=True);syntax.append((f,r.returncode,r.stderr))
t10_detail={'entrypoint':needed,'syntax':syntax,'actual_entrypoint':None};t10_ok=all(x in idx for x in needed) and all(r==0 for _,r,_ in syntax)
if a.entrypoint_url:
 with sync_playwright() as p2:
  b2=p2.chromium.launch(executable_path=a.browser,headless=True,args=['--no-sandbox','--disable-dev-shm-usage']);pg=b2.new_page();errors=[];pg.on('pageerror',lambda e: errors.append(str(e)));pg.route('https://ctcoqgsztdtsazdiwcmd.supabase.co/**',lambda route: route.fulfill(status=401,content_type='application/json',body='{}'));resp=pg.goto(a.entrypoint_url,wait_until='domcontentloaded');pg.wait_for_timeout(1500);resources=pg.evaluate("performance.getEntriesByType('resource').map(x=>x.name)");actual=pg.evaluate("({controller:!!window.PablicusController,chatList:!!window.PablicusChatListView})");t10_detail['actual_entrypoint']={'status':resp.status if resp else None,'errors':errors,'actual':actual,'resources':[x for x in resources if 'app-controller.js' in x or 'chat-list-view.js' in x]};t10_ok=t10_ok and resp and resp.status==200 and not errors and actual['controller'] and actual['chatList'] and len(t10_detail['actual_entrypoint']['resources'])==2;b2.close()
record('B1-T10',t10_ok,t10_detail)
(out/'acceptance-results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
print(json.dumps(results,ensure_ascii=False,indent=2))
