const API='https://ctcoqgsztdtsazdiwcmd.supabase.co/functions/v1/public-bot-core';
const PUBLIC_KEY='sb_publishable_kMGqZAM2vadfXbBr8r5uzw_l9EiBtIw';
const AUTH='sb-ctcoqgsztdtsazdiwcmd-auth-token';
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID();
let identity=null,report=null,manifest=null,busy=false,pinned=null,activeChat=null,activeBot=null,chatBusy=false,chatEpoch=0;
function sessionToken(){try{if(JSON.parse(localStorage.getItem('pablicus:passkey-unvalidated'))===true)return null;const x=JSON.parse(localStorage.getItem(AUTH)||'null');return x?.access_token||x?.currentSession?.access_token||x?.session?.access_token||null;}catch{return null;}}
function status(message,bad=false){$('state').textContent=message;$('state').className=bad?'bad':'good';}
function sameSession(token){if(!token||sessionToken()!==token)throw Error('Вход изменился. Нажми «Проверить вход».');}
async function request(path,{method='GET',data,token=pinned,keyToken=null,anonymous=false}={}){
 if(!anonymous)sameSession(token);
 const headers={apikey:PUBLIC_KEY,...(!anonymous?{Authorization:`Bearer ${keyToken||token}`}:{})};if(data!==undefined)headers['Content-Type']='application/json';
 const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),20000);let response;
 try{response=await fetch(API+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data),signal:ctrl.signal,cache:'no-store'});}catch{throw Error('Сервер не ответил. Запись могла сохраниться; не нажимай повторно без проверки истории.');}finally{clearTimeout(timer);}
 if(!anonymous)sameSession(token);
 let body;try{body=await response.json();}catch{throw Error('Не удалось прочитать ответ сервера.');}
 return{status:response.status,body};
}
async function ok(path,opts={},expected=200){const r=await request(path,opts);if(r.status!==expected)throw Error(`${r.body?.error?.message||'Ошибка сервера'} [${r.status}; ${r.body?.error?.code||'HTTP'}; ${r.body?.request_id||'нет ID'}]`);return r.body;}
function controls(){const ready=!!identity&&!busy;$('run').disabled=!ready;$('peerCheck').disabled=!ready;$('connect').disabled=busy;$('copyReport').disabled=!report;$('saveReport').disabled=!report;$('copyPeer').disabled=!manifest;const found=ready&&!!manifest?.bots?.length;for(const id of ['botSelect','openChat','showRecords','stop'])$(id).disabled=!found;const chatting=ready&&!chatBusy&&activeChat&&activeBot?.status==='active';for(const id of ['send','message','restart'])$(id).disabled=!chatting;for(const b of $('choices').querySelectorAll('button'))b.disabled=!chatting;}
function clearUser(){identity=null;pinned=null;activeChat=null;activeBot=null;manifest=null;report=null;++chatEpoch;$('identity').textContent='';$('thread').replaceChildren();$('choices').replaceChildren();$('checks').replaceChildren();$('records').textContent='';$('peerResult').textContent='';$('peerInput').value='';$('reportText').value='';$('reportText').hidden=true;$('summary').textContent='Вход не подтверждён.';controls();}
const stateKey=()=>`public-bot-lab:v1:${identity?.id}`;
function persist(){if(!identity)return;try{localStorage.setItem(stateKey(),JSON.stringify({report,manifest}));}catch{}}
function loadSaved(){try{const s=JSON.parse(localStorage.getItem(stateKey())||'null');if(s?.manifest?.owner_id===identity.id){manifest=s.manifest;report=s.report;renderChecks();fillBots();}}catch{}}
function fillBots(){$('botSelect').replaceChildren();for(const b of manifest?.bots||[]){const o=document.createElement('option');o.value=b.id;o.textContent=b.label;$('botSelect').append(o);}controls();}
async function connect(){if(busy)return;clearUser();const token=sessionToken();$('loginHelp').hidden=!!token;if(!token){status('Сначала войди в Public в этом браузере.',true);return;}status('Проверяю обычный вход…');try{pinned=token;const me=await ok('/v1/me');if(me.scope!=='manage')throw Error('Нужен вход пользователя Public, а не ключ бота.');identity=me;$('identity').textContent='Аккаунт подтверждён: '+me.id;status('Вход подтверждён. Можно запускать проверку.');$('loginHelp').hidden=true;loadSaved();}catch(e){clearUser();$('loginHelp').hidden=false;status(e.message,true);}controls();}
function renderChecks(){$('checks').replaceChildren();for(const c of report?.checks||[]){const li=document.createElement('li');li.className=c.pass?'good':'bad';li.textContent=(c.pass?'✓ ':'✕ ')+c.name+(c.status?` · HTTP ${c.status}`:'');$('checks').append(li);}if(report){const failed=report.checks.filter(x=>!x.pass).length,passed=report.checks.filter(x=>x.pass).length;$('summary').textContent=report.complete?`Проверка текущего аккаунта: ${passed} успешно, ${failed} ошибок. Второй аккаунт: ${report.peer?.complete?'проверен':'ещё не проверен'}.`:(report.failure?`Проверка остановлена: ${report.failure}`:busy?'Проверка выполняется…':'Предыдущая проверка не завершена. Скопируй результат.');$('summary').className=failed||report.failure?'small bad':report.complete?'small good':'small muted';}controls();}
function check(name,pass,detail={}){report.checks.push({name,pass:!!pass,...detail});renderChecks();persist();if(!pass)throw Error('Не пройдена проверка: '+name);}
async function tested(name,path,opts={},expected=200,code){const r=await request(path,opts);check(name,r.status===expected&&(!code||r.body?.error?.code===code),{status:r.status,...(r.body?.error?.code?{code:r.body.error.code}:{})});return r.body;}
const sendTurn=(chat,text,revision,id=uid(),extra={})=>request(`/v1/chats/${chat}/messages`,{...extra,method:'POST',data:{id,text,revision}});
async function run(){if(busy||!identity)return;if(manifest&&!confirm('Создать новую отдельную проверку? Предыдущие тестовые боты останутся сохранёнными.'))return;busy=true;activeChat=null;activeBot=null;controls();const token=pinned;report={version:1,project:'ctcoqgsztdtsazdiwcmd',started_at:new Date().toISOString(),checks:[],complete:false,peer:null};manifest={version:1,project:report.project,run_id:uid(),owner_id:identity.id,bots:[],chat_id:null};let key=null,publicBot=null;
 try{
  await tested('Сервер доступен','/health',{anonymous:true});await tested('Без входа доступ запрещён','/v1/me',{anonymous:true},401,'UNAUTHORIZED');
  const me=await tested('Обычный аккаунт подтверждён','/v1/me');check('Сервер определил правильного владельца',me.id===identity.id);
  const make=async(template,label)=>{const b=await tested('Создание бота: '+label,'/v1/bots',{method:'POST',data:{name:'Тест Public '+manifest.run_id.slice(0,8)+' · '+label,template,visibility:'private'}},201);manifest.bots.push({id:b.id,label});persist();check('Бот принадлежит текущему аккаунту',b.owner_id===identity.id);return b;};
  let intake=await make('intake','Заявка'),help=await make('help','Справка');
  manifest.bot_id=intake.id;
  const newChat=async(bot)=>{const id=uid();const c=await tested('Создание диалога','/v1/bots/'+bot.id+'/chats',{method:'POST',data:{id}},201);return c;};
  const chat=await newChat(intake);manifest.chat_id=chat.id;persist();let revision=0;
  for(const text of ['/start','Тестовый пользователь','test@example.com','morning']){const r=await sendTurn(chat.id,text,revision);check('Ответ бота, шаг '+(revision+1),r.status===200&&r.body.revision===revision+1&&Array.isArray(r.body.replies),{status:r.status});revision=r.body.revision;}
  const event=uid(),race=await Promise.all([sendTurn(chat.id,'yes',revision,event),sendTurn(chat.id,'yes',revision,event)]);
  check('Двойная отправка возвращает одно подтверждение',race.every(x=>x.status===200)&&race[0].body.revision===5&&race[0].body.replies[0].id===race[1].body.replies[0].id);
  const records=await tested('Чтение пробной заявки',`/v1/bots/${intake.id}/records`);check('Сохранена ровно одна заявка',records.records.length===1);
  const changed=await sendTurn(chat.id,'no',revision,event);check('Подмена повторного сообщения запрещена',changed.status===409&&changed.body.error?.code==='IDEMPOTENCY_CONFLICT',{status:changed.status});
  const hist=await tested('История повторно загружена с сервера','/v1/chats/'+chat.id);check('Сохранены пять шагов диалога',hist.session.revision===5&&hist.events.length===5);
  const hc=await newChat(help);check('Справочный бот отвечает',(await sendTurn(hc.id,'/start',0)).status===200);
  const parallel=await Promise.all([sendTurn(hc.id,'about',1),sendTurn(hc.id,'privacy',1)]);check('Параллельные изменения: одно принято, второе отклонено',parallel.filter(x=>x.status===200).length===1&&parallel.filter(x=>x.status===409&&x.body.error?.code==='REVISION_CONFLICT').length===1);
  intake=await tested('Бот остановлен','/v1/bots/'+intake.id,{method:'PATCH',data:{revision:intake.revision,status:'stopped'}});const stopped=await sendTurn(chat.id,'/start',5);check('Остановленный бот не отвечает на новое сообщение',stopped.status===409&&stopped.body.error?.code==='BOT_STOPPED',{status:stopped.status});
  intake=await tested('Бот включён снова','/v1/bots/'+intake.id,{method:'PATCH',data:{revision:intake.revision,status:'active'}});check('После включения ответ получен',(await sendTurn(chat.id,'/start',5)).status===200);
  help=await tested('Подготовлен тест ограниченного ключа','/v1/bots/'+help.id,{method:'PATCH',data:{revision:help.revision,visibility:'public'}});publicBot=help;
  key=await tested('Выпущен временный ключ только для общения','/v1/keys',{method:'POST',data:{bot_id:help.id,label:'Bot Lab temporary test',days:1}},201);
  await tested('Ключ работает','/v1/me',{keyToken:key.token});await tested('Ключ не может управлять ботами','/v1/bots',{keyToken:key.token},403,'FORBIDDEN');await tested('Ключ не может открыть другого бота',`/v1/bots/${intake.id}/chats`,{keyToken:key.token,method:'POST',data:{id:uid()}},404,'NOT_FOUND');
  await tested('Ключ отозван','/v1/keys/'+key.id,{method:'DELETE'});await tested('Отозванный ключ больше не работает','/v1/me',{keyToken:key.token},401,'UNAUTHORIZED');key=null;
  help=await tested('Справочный бот снова закрыт','/v1/bots/'+help.id,{method:'PATCH',data:{revision:help.revision,visibility:'private'}});publicBot=null;
  report.complete=true;report.finished_at=new Date().toISOString();status('Проверка текущего аккаунта завершена. Скопируй результат.');
 }catch(e){if(sessionToken()!==token){clearUser();status('Вход изменился. Проверка остановлена.',true);return;}report.failure=e.message;status('Проверка остановилась. Скопируй результат — повторять вслепую не нужно.',true);}
 finally{if(report&&sessionToken()===token){if(key){try{await ok('/v1/keys/'+key.id,{method:'DELETE'});}catch{report.cleanup_warning='Не подтверждён отзыв тестового ключа. Останови тестовых ботов.';}}if(publicBot){try{const b=await ok('/v1/bots/'+publicBot.id);await ok('/v1/bots/'+b.id,{method:'PATCH',data:{revision:b.revision,visibility:'private',status:'stopped'}});}catch{report.cleanup_warning='Не подтверждено закрытие тестового бота. Нажми «Остановить тестовых ботов».';}}persist();renderChecks();fillBots();}busy=false;controls();}
 if(report?.complete)await openChat();
}
function bubble(who,text){const n=document.createElement('div');n.className='bubble '+who;n.textContent=text;$('thread').append(n);$('thread').scrollTop=$('thread').scrollHeight;}
function replies(values){for(const r of values||[])bubble('bot',r.text||'');$('choices').replaceChildren();const last=(values||[]).at(-1);for(const item of last?.buttons||[]){const b=document.createElement('button');b.type='button';b.textContent=item.label;b.onclick=()=>manualSend(item.value||item.id);$('choices').append(b);}controls();}
async function openChat(){if(!identity||busy||chatBusy)return;const id=$('botSelect').value;if(!id)return;const epoch=++chatEpoch;chatBusy=true;controls();try{const bot=await ok('/v1/bots/'+id),list=await ok(`/v1/bots/${id}/chats`);if(epoch!==chatEpoch)return;activeBot=bot;let chat=list.chats[0];if(!chat)chat=await ok(`/v1/bots/${id}/chats`,{method:'POST',data:{id:uid()}},201);if(epoch!==chatEpoch)return;activeChat=chat;await history(epoch);$('chatStatus').textContent=bot.status==='active'?'Переписка с настоящим сервером.':'Бот остановлен.';}catch(e){$('chatStatus').textContent=e.message;}finally{chatBusy=false;controls();}}
async function history(epoch=chatEpoch){if(!activeChat)return;let after=0,all=[],h;do{h=await ok('/v1/chats/'+activeChat.id+'?after='+after);all.push(...h.events);after=h.next_after;}while(h.has_more&&all.length<1000);if(epoch!==chatEpoch)return;activeChat=h.session;$('thread').replaceChildren();$('choices').replaceChildren();for(const ev of all){bubble('me',ev.input.text);replies(ev.response.replies);}if(!all.length)bubble('bot','Нажми «Начать заново», чтобы запустить сценарий.');}
async function manualSend(text){if(busy||chatBusy||!activeChat||activeBot?.status!=='active'||!text?.trim())return;chatBusy=true;const epoch=chatEpoch;controls();try{await ok('/v1/chats/'+activeChat.id+'/messages',{method:'POST',data:{id:uid(),text,revision:activeChat.revision}});if(epoch!==chatEpoch)return;$('message').value='';await history(epoch);$('chatStatus').textContent='Ответ сохранён на сервере.';}catch(e){$('chatStatus').textContent=e.message+' Сначала обнови переписку.';try{await history(epoch);}catch{}}finally{chatBusy=false;controls();}}
async function showRecords(){if(!manifest)return;try{const r=await ok(`/v1/bots/${manifest.bot_id}/records`);$('records').textContent=JSON.stringify(r.records.map(x=>({kind:x.kind,data:x.data,created_at:x.created_at})),null,2);}catch(e){$('records').textContent=e.message;}}
async function stop(){if(busy||!manifest)return;busy=true;controls();try{for(const b of manifest.bots){const row=await ok('/v1/bots/'+b.id);await ok('/v1/bots/'+b.id,{method:'PATCH',data:{revision:row.revision,status:'stopped',visibility:'private'}});}if(activeBot)activeBot.status='stopped';status('Оба тестовых бота остановлены. Обычные чаты не изменены.');}catch(e){status(e.message,true);}finally{busy=false;controls();}}
async function copy(value){$('reportText').hidden=false;$('reportText').value=value;try{await navigator.clipboard.writeText(value);$('summary').textContent='Скопировано. Вставь результат в чат с Эмбер.';}catch{$('reportText').focus();$('reportText').select();$('summary').textContent='Текст выделен ниже. Выбери «Копировать» и вставь в чат с Эмбер.';}}
function peerCode(){return{version:1,project:'ctcoqgsztdtsazdiwcmd',run_id:manifest.run_id,owner_id:manifest.owner_id,bot_id:manifest.bot_id,chat_id:manifest.chat_id};}
async function peerCheck(){if(busy||!identity||!report?.complete){$('peerResult').textContent='Сначала пройди проверку текущего аккаунта.';return;}let p;try{p=JSON.parse($('peerInput').value);const re=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;if(p.version!==1||p.project!=='ctcoqgsztdtsazdiwcmd'||!['run_id','owner_id','bot_id','chat_id'].every(k=>re.test(p[k])))throw Error('Нужен полный код из первого аккаунта.');if(p.owner_id===identity.id)throw Error('Сейчас открыт тот же аккаунт. Войди другим разрешённым пользователем в другом браузере.');}catch(e){$('peerResult').textContent=e.message;return;}
 busy=true;controls();const result={complete:false,first_owner:p.owner_id,second_owner:identity.id,checks:[]};try{const targets=[['Чужой бот закрыт','/v1/bots/'+p.bot_id],['Чужая история закрыта','/v1/chats/'+p.chat_id],['Чужие заявки закрыты',`/v1/bots/${p.bot_id}/records`]];for(const [name,path]of targets){const r=await request(path);const pass=r.status===404&&r.body.error?.code==='NOT_FOUND';result.checks.push({name,pass,status:r.status});if(!pass)throw Error(name+': получен неожиданный ответ.');}const r=await request(`/v1/bots/${p.bot_id}/chats`,{method:'POST',data:{id:uid()}});result.checks.push({name:'Нельзя открыть диалог с закрытым чужим ботом',pass:r.status===404&&r.body.error?.code==='NOT_FOUND',status:r.status});result.complete=result.checks.every(x=>x.pass);$('peerResult').textContent=result.complete?'Четыре проверки разделения доступа пройдены. Скопируй результат общей кнопкой выше.':'Есть ошибка разделения доступа.';}catch(e){result.failure=e.message;$('peerResult').textContent=e.message;}finally{busy=false;if(report){report.peer=result;persist();renderChecks();}controls();}}
$('connect').onclick=connect;$('run').onclick=run;$('openChat').onclick=openChat;$('restart').onclick=()=>manualSend('/start');$('showRecords').onclick=showRecords;$('stop').onclick=stop;$('sendForm').onsubmit=e=>{e.preventDefault();manualSend($('message').value);};$('copyReport').onclick=()=>copy(JSON.stringify(report,null,2));$('copyPeer').onclick=()=>copy(JSON.stringify(peerCode(),null,2));$('peerCheck').onclick=peerCheck;
$('saveReport').onclick=()=>{if(!report)return;const u=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='Public-Bot-Lab-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
window.addEventListener('storage',e=>{if(e.key===AUTH||e.key==='pablicus:passkey-unvalidated'){if(sessionToken()!==pinned){clearUser();$('loginHelp').hidden=false;status('Вход изменился. Нажми «Проверить вход».',true);}}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&pinned&&sessionToken()!==pinned){clearUser();$('loginHelp').hidden=false;status('Вход обновился. Нажми «Проверить вход».',true);}});
connect();
