import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const A='10000000-0000-4000-8000-000000000001',B='10000000-0000-4000-8000-000000000002',C='10000000-0000-4000-8000-000000000003',D='10000000-0000-4000-8000-000000000004',EMPTY='10000000-0000-4000-8000-000000000005';
const CHAT='20000000-0000-4000-8000-000000000001',FOREIGN='20000000-0000-4000-8000-000000000002',SAVED='20000000-0000-4000-8000-000000000003';
const id=n=>'30000000-0000-4000-8000-'+String(n).padStart(12,'0'),TODAY='2026-09-09';
test('exact shared task list SQL: pagination, filters, read-only authorization',async t=>{
 const db=new PGlite();
 try{
  for(const f of ['schema-fixture.sql','SCHEMA_PROPOSAL.sql','REPLY_SCHEMA_PROPOSAL.sql','ACTIONS_SCHEMA_PROPOSAL.sql'])await db.exec(await readFile(new URL(f,import.meta.url),'utf8'));
  await db.exec('ALTER TABLE profiles ADD COLUMN display_name text;ALTER TABLE profiles ADD COLUMN email text');
  for(const f of ['CANVAS_SCHEMA_PROPOSAL.sql','TASKS_SCHEMA_PROPOSAL.sql'])await db.exec(await readFile(new URL(f,import.meta.url),'utf8'));
  await db.query('update profiles set display_name=$1,email=$2 where id=$3',['Katya','private@example.invalid',B]);
  await db.query('update profiles set display_name=$1 where id=$2',['Suspended secret',D]);
  await db.query('update conversations set title=$1,type=$2 where id=$3',['Избранное','group',SAVED]);
  await db.query('insert into profiles(id,username,is_approved) values($1,$2,true)',[EMPTY,'empty_user']);
  const as=async(uid,sql,args=[],role='authenticated')=>{await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid||'']);await db.exec(`SET ROLE ${role}`);try{return(await db.query(sql,args)).rows;}finally{await db.exec('RESET ROLE');}};
  const list=async({uid=A,role='authenticated',view='open',query='',today=TODAY,cursor=null,limit=40}={})=>(await as(uid,'select public.pablicus_list_tasks($1,$2,$3,$4,$5) as data',[view,query,today,cursor===null?null:JSON.stringify(cursor),limit],role))[0].data;
  const ids=p=>p.tasks.map(x=>x.id),rows=[];
  const all=async(opts={})=>{let cursor=null;const out=[];do{const p=await list({...opts,cursor});out.push(...p.tasks);cursor=p.next_cursor;}while(cursor);return out;};
  await t.test('empty/approved users get empty list without creating canvases',async()=>{assert.deepEqual(await list(),{tasks:[],next_cursor:null});assert.deepEqual(await list({uid:EMPTY}),{tasks:[],next_cursor:null});assert.equal((await db.query('select count(*) from pablicus_chat_private.conversation_canvases')).rows[0].count,0);});
  const source=(await db.query(`insert into messages(client_message_id,conversation_id,server_seq,sender_id,body) values(gen_random_uuid(),$1,1,$2,'SOURCE CONTENT MUST NOT LEAK') returning id`,[CHAT,A])).rows[0].id;
  for(let n=1;n<=96;n++){
   const r={id:id(n),conversation_id:n%4===0?FOREIGN:n%4===1?SAVED:CHAT,title:n===7?'Review 50% of shot_A':n===11?'Review 50x of shotBA':n===15?'ПОДГОТОВИТЬ СЦЕНАРИЙ':'Task '+n,completed:n%5===0,assignee_id:n%3===0?null:n%3===1?A:B,due_date:[null,'2026-09-08',TODAY,'2026-09-10'][n%4],created_at:`2026-09-09T12:00:${String(Math.floor(n/3)).padStart(2,'0')}.123456+00:00`,deleted_at:n===18?'2026-09-09T13:00:00Z':null};rows.push(r);
   await db.query(`insert into pablicus_chat_private.canvas_tasks(id,conversation_id,title,assignee_id,due_date,completed,created_at,updated_at,created_by,updated_by,source_message_id,source_block_id,deleted_at,create_payload) values($1,$2,$3,$4,$5,$6,$7,$7,$8,$8,$9,$10,$11,'{"secret":"replay only"}')`,[r.id,r.conversation_id,r.title,r.assignee_id,r.due_date,r.completed,r.created_at,A,n===7?source:null,n===7?'block_1':null,r.deleted_at]);
  }
  const expected=(view='open',query='')=>rows.filter(x=>x.conversation_id!==FOREIGN&&!x.deleted_at&&x.completed===(view==='completed')&&(view!=='mine'||x.assignee_id===A)&&(view!=='overdue'||x.due_date&&x.due_date<TODAY)&&x.title.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id));
  await t.test('open includes all accessible assignees, never deleted/foreign/completed tasks',async()=>{const p=await list();assert.equal(p.tasks.length,40);assert.ok(p.next_cursor);const a=await all();assert.deepEqual(a.map(x=>x.id),expected().map(x=>x.id));assert.ok(a.some(x=>x.assignee_id===B));assert.ok(a.some(x=>x.assignee_id===null));});
  await t.test('mine, overdue and completed have exact assignment and due-date rules',async()=>{for(const view of ['mine','overdue','completed'])assert.deepEqual((await all({view})).map(x=>x.id),expected(view).map(x=>x.id));const a=await all({view:'overdue',today:'2026-09-10'});assert.ok(a.some(x=>x.due_date===TODAY));assert.ok(a.every(x=>x.due_date<'2026-09-10'&&!x.completed));});
  await t.test('search trims, folds case and treats percent/underscore literally; title only',async()=>{for(const query of ['  REVIEW 50% ','shot_A','%','_'])assert.deepEqual(ids(await list({query})),[id(7)]);assert.deepEqual(ids(await list({query:'подготовить',view:'completed'})),[id(15)]);for(const query of ['Katya',"' OR true --",'source content'])assert.deepEqual(ids(await list({query})),[]);});
  await t.test('keyset pagination preserves six timestamp decimals and covers UUID ties once',async()=>{let cursor=null;const seen=[];do{const p=await list({limit:7,cursor});assert.ok(p.tasks.length<=7);seen.push(...ids(p));if(p.next_cursor){assert.deepEqual(Object.keys(p.next_cursor).sort(),['created_at','id']);assert.match(p.next_cursor.created_at,/\.123456/);assert.equal(p.next_cursor.id,p.tasks.at(-1).id);assert.equal(p.next_cursor.created_at,p.tasks.at(-1).created_at);}cursor=p.next_cursor;}while(cursor);assert.deepEqual(seen,expected().map(x=>x.id));assert.equal(new Set(seen).size,seen.length);assert.ok(expected().some((x,i,a)=>i&&a[i-1].created_at===x.created_at));});
  await t.test('exact terminal page and empty boundary have null next cursor',async()=>{assert.equal((await list({query:'50%',limit:1})).next_cursor,null);const count=expected('completed').length,p=await list({view:'completed',limit:count});assert.equal(p.tasks.length,count);assert.equal(p.next_cursor,null);assert.deepEqual(await list({cursor:{created_at:'1900-01-01T00:00:00Z',id:id(1)}}),{tasks:[],next_cursor:null});});
  await t.test('labels follow conversation list; response excludes email/replay/source content',async()=>{const a=await all(),peer=a.find(x=>x.conversation_id===CHAT);assert.equal(peer.conversation_title,'Katya');assert.equal(a.find(x=>x.conversation_id===SAVED).conversation_title,'Избранное');assert.equal(a.find(x=>x.conversation_id===CHAT&&x.assignee_id===B).assignee_name,'Katya');assert.equal(a.find(x=>x.conversation_id===SAVED&&x.assignee_id===B).assignee_name,null);assert.equal(a.find(x=>x.assignee_id===A).assignee_name,'@member_a');assert.deepEqual(Object.keys(peer).sort(),['id','title','assignee_id','due_date','completed','revision','source_message_id','source_block_id','created_at','created_by','updated_at','updated_by','conversation_id','conversation_title','assignee_name'].sort());for(const text of ['private@example.invalid','replay only','SOURCE CONTENT'])assert.ok(!JSON.stringify(a).includes(text));const s=a.find(x=>x.id===id(7));assert.equal(s.source_message_id,source);assert.equal(s.source_block_id,'block_1');await db.query('update profiles set display_name=$1 where id=$2',[' ',B]);assert.equal((await list()).tasks.find(x=>x.conversation_id===CHAT).conversation_title,'@member_b');await db.query('update profiles set display_name=$1 where id=$2',['Katya',B]);});
  await t.test('removed assignee has null name; removed caller membership vanishes also on page two',async()=>{await db.query('delete from conversation_members where conversation_id=$1 and user_id=$2',[CHAT,B]);let a=await all();assert.ok(a.filter(x=>x.conversation_id===CHAT&&x.assignee_id===B).every(x=>x.assignee_name===null));assert.ok(a.filter(x=>x.conversation_id===CHAT).every(x=>x.conversation_title==='Диалог'));assert.deepEqual(await list({uid:B}),{tasks:[],next_cursor:null});await db.query('insert into conversation_members(conversation_id,user_id) values($1,$2)',[CHAT,B]);const p=await list({limit:1});await db.query('delete from conversation_members where conversation_id=$1 and user_id=$2',[CHAT,A]);assert.ok((await all()).every(x=>x.conversation_id===SAVED));assert.ok((await list({cursor:p.next_cursor})).tasks.every(x=>x.conversation_id===SAVED));await db.query('insert into conversation_members(conversation_id,user_id) values($1,$2)',[CHAT,A]);});
  await t.test('revoking approval denies caller between pages and removes assignee names',async()=>{await db.query('update profiles set is_approved=false where id=$1',[B]);await assert.rejects(list({uid:B}),{code:'42501'});const a=await all();assert.ok(a.filter(x=>x.assignee_id===B).every(x=>x.assignee_name===null));assert.ok(a.filter(x=>x.conversation_id===CHAT).every(x=>x.conversation_title==='Диалог'));await db.query('update profiles set is_approved=true where id=$1',[B]);const p=await list({limit:1});await db.query('update profiles set is_approved=false where id=$1',[A]);await assert.rejects(list({cursor:p.next_cursor}),{code:'42501'});await db.query('update profiles set is_approved=true where id=$1',[A]);});
  await t.test('forged/foreign cursor is only an order boundary, never conversation authorization',async()=>{const theirs=await all({uid:C});assert.ok(theirs.length>0);assert.ok(theirs.every(x=>x.conversation_id===FOREIGN));const cursor={created_at:rows.at(-1).created_at,id:rows.at(-1).id};assert.ok((await list({cursor})).tasks.every(x=>x.conversation_id!==FOREIGN));assert.ok((await list({uid:C,cursor})).tasks.every(x=>x.conversation_id===FOREIGN));});
  await t.test('missing/unknown/suspended identities and anon are denied for both callable functions',async()=>{for(const uid of [null,D,EMPTY.replace(/5$/,'9')]){await assert.rejects(list({uid}),{code:'42501'});await assert.rejects(as(uid,'select pablicus_chat_private.list_tasks()'),{code:'42501'});}await assert.rejects(list({uid:A,role:'anon'}),{code:'42501'});await assert.rejects(as(A,'select pablicus_chat_private.list_tasks()',[],'anon'),{code:'42501'});});
  await t.test('invalid params fail; explicit limit60 and omitted defaults work',async()=>{for(const view of [null,'all','OPEN',''])await assert.rejects(list({view}),{code:'22023'});for(const query of [null,'x'.repeat(201),'🙂'.repeat(201)])await assert.rejects(list({query}),{code:'22023'});for(const limit of [null,0,-1,61,999999])await assert.rejects(list({limit}),{code:'22023'});for(const today of [null,'infinity','-infinity','1899-12-31','10000-01-01'])await assert.rejects(list({today}),{code:'22023'});assert.equal((await list({limit:60})).tasks.length,expected().length);assert.equal((await list({query:'x'.repeat(200)})).tasks.length,0);assert.equal((await as(A,'select public.pablicus_list_tasks() as data'))[0].data.tasks.length,40);});
  await t.test('cursor rejects extra fields, invalid types, nonfinite/timezone-free/malformed dates',async()=>{const good={created_at:rows[40].created_at,id:rows[40].id};for(const cursor of [{},[],3,'x',{...good,extra:true},{id:good.id},{created_at:good.created_at},{...good,id:1},{...good,id:null},{...good,id:'no'},{...good,created_at:null},{...good,created_at:'infinity'},{...good,created_at:'2026-09-09'},{...good,created_at:'2026-99-09T01:02:03Z'},{...good,created_at:'2026-09-09T01:02:03'},{...good,created_at:'2026-09-09T01:02:03.1234567Z'}])await assert.rejects(list({cursor}),{code:'22023'});assert.ok((await list({cursor:good})).tasks.length>0);});
  await t.test('newer insert/edit/deleted boundary cannot duplicate older page IDs',async()=>{const p=await list({limit:7}),cursor=p.next_cursor;await db.query(`insert into pablicus_chat_private.canvas_tasks(id,conversation_id,title,created_at,create_payload) values($1,$2,'New task','2026-09-09T14:00:00Z','{}')`,[id(999),CHAT]);await db.query("update pablicus_chat_private.canvas_tasks set title='Edited still older',updated_at=now() where id=$1",[expected().at(-1).id]);await db.query('update pablicus_chat_private.canvas_tasks set deleted_at=now() where id=$1',[cursor.id]);const second=await list({cursor,limit:60});assert.ok(!ids(second).includes(id(999)));assert.ok(ids(second).every(x=>!ids(p).includes(x)));assert.ok(ids(second).includes(expected().at(-1).id));assert.equal((await list()).tasks[0].id,id(999));await db.query('delete from pablicus_chat_private.canvas_tasks where id=$1',[id(999)]);await db.query('update pablicus_chat_private.canvas_tasks set deleted_at=null where id=$1',[cursor.id]);});
  await t.test('list never mutates tasks/canvases or message read markers',async()=>{const snapshot=async()=>(await db.query(`select (select jsonb_agg(to_jsonb(t) order by id) from pablicus_chat_private.canvas_tasks t) tasks,(select jsonb_agg(to_jsonb(c)) from pablicus_chat_private.conversation_canvases c) canvases,(select jsonb_agg(to_jsonb(m) order by conversation_id,user_id) from conversation_members m) members`)).rows[0];const before=await snapshot();await all();await all({view:'mine'});await all({view:'completed'});assert.deepEqual(await snapshot(),before);});
  await t.test('private tables still denied; wrapper/implementation ACL, locks and search_path are explicit',async()=>{for(const table of ['canvas_tasks','conversation_canvases'])for(const verb of ['select * from','delete from'])await assert.rejects(as(A,`${verb} pablicus_chat_private.${table}`),{code:'42501'});const defs=(await db.query(`select n.nspname,p.prosecdef,p.proconfig,has_function_privilege('anon',p.oid,'execute') anon,has_function_privilege('authenticated',p.oid,'execute') authenticated,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='public' and p.proname='pablicus_list_tasks') or (n.nspname='pablicus_chat_private' and p.proname='list_tasks')`)).rows;assert.equal(defs.length,2);for(const d of defs){assert.equal(d.prosecdef,d.nspname==='pablicus_chat_private');assert.ok(d.proconfig.includes('search_path=""'));assert.equal(d.anon,false);assert.equal(d.authenticated,true);}const impl=defs.find(x=>x.prosecdef).definition;assert.match(impl,/FOR SHARE OF cm/);assert.match(impl,/p\.is_approved FOR SHARE/);assert.equal((await db.query("select indexname from pg_indexes where indexname='canvas_tasks_global_live_order_idx'")).rows.length,1);});
 }finally{await db.close();}
});
