(()=>{'use strict';
const URL='https://ctcoqgsztdtsazdiwcmd.supabase.co',KEY='sb_publishable_kMGqZAM2vadfXbBr8r5uzw_l9EiBtIw';
const FN=URL+'/functions/v1/pablicus-auth-handoff',APP=location.origin+location.pathname,STORE='pablicus:pwa-auth-handoff';
const client=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),notice=t=>{const n=$('loginNotice');if(n)n.textContent=t},error=t=>{const n=$('loginError');if(n)n.textContent=t||''};
const random=()=>{const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')};
async function call(action,handoff,token){const headers={'content-type':'application/json','apikey':KEY};if(token)headers.authorization='Bearer '+token;const r=await fetch(FN,{method:'POST',headers,body:JSON.stringify({action,handoff}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'auth_handoff_failed');return d}
async function finishSafari(){const h=new URL(location.href).searchParams.get('pwa_handoff');if(!h)return false;notice('Подтверждаю вход для приложения…');let session=null;for(let i=0;i<30&&!session;i++){session=(await client.auth.getSession()).data.session;if(!session)await new Promise(r=>setTimeout(r,250))}if(!session){error('Ссылка подтверждена не полностью. Откройте её ещё раз из письма.');return true}try{await call('complete',h,session.access_token);history.replaceState({},'',APP);notice('Готово. Вернитесь на главный экран iPhone и откройте Pablicus — вход завершится автоматически.');return true}catch(e){error('Не удалось передать вход приложению. Повторите ссылку из письма.');return true}}
let claiming=false;
async function claim(){if(claiming)return;const h=localStorage.getItem(STORE);if(!h)return;claiming=true;try{const d=await call('claim',h);if(d.expired){localStorage.removeItem(STORE);notice('Ссылка истекла. Запросите новую.');return}if(!d.ready){notice('Письмо отправлено. После подтверждения вернитесь в Pablicus.');return}notice('Завершаю вход…');const r=await client.auth.verifyOtp({token_hash:d.token_hash,type:'email'});if(r.error)throw r.error;await call('consume',h).catch(()=>{});localStorage.removeItem(STORE);location.replace(APP)}catch(e){console.warn('Pablicus handoff claim failed',e);error('Не удалось завершить вход. Запросите новую ссылку.')}finally{claiming=false}}
document.addEventListener('submit',async e=>{if(e.target?.id!=='magicForm')return;e.preventDefault();e.stopImmediatePropagation();const button=$('magicSubmit'),email=$('email')?.value.trim();if(!email)return;button.disabled=true;error('');try{const h=random();localStorage.setItem(STORE,h);const redirect=APP+'?pwa_handoff='+encodeURIComponent(h);const r=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:redirect}});if(r.error)throw r.error;notice('Письмо отправлено. Нажмите ссылку в письме, затем просто вернитесь в Pablicus.')}catch(e){localStorage.removeItem(STORE);error(e.message||'Не удалось отправить ссылку')}finally{button.disabled=false}},true);
finishSafari().then(done=>{if(!done)claim()});
setInterval(()=>{if(document.visibilityState==='visible')claim()},2500);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')claim()});window.addEventListener('pageshow',claim);
})();