/* Public Bot Core UI integration. Uses the existing signed-in Supabase session. */
(function(global){'use strict';
 const API='https://ctcoqgsztdtsazdiwcmd.supabase.co/functions/v1/public-bot-core',uuid=()=>crypto.randomUUID();
 const element=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 function create({client,getUser,onError}){let host=null,epoch=0,bots=[],activeBot=null,activeChat=null,busy=false;
  const current=(ticket,userId)=>ticket===epoch&&host?.isConnected&&getUser()?.id===userId;
  async function token(){const r=await client.auth.getSession(),t=r.data?.session?.access_token;if(!t)throw Error('Войдите в Public заново.');return t;}
  async function request(path,{method='GET',data}={}){const user=getUser();if(!user)throw Error('Войдите в Public.');const access=await token();if(getUser()?.id!==user.id)throw Error('Аккаунт изменился.');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),20000);let response;try{response=await fetch(API+path,{method,headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store',signal:ctrl.signal});}finally{clearTimeout(timer);}let body;try{body=await response.json();}catch{throw Error('Сервер ботов вернул некорректный ответ.');}if(!response.ok)throw Error(body?.error?.message||('Ошибка Bot Core · '+response.status));return body;}
  const fail=e=>onError?.(e);function header(parent,title,back){const h=element('div','botsHeader');if(back){const b=element('button','botsBack','‹');b.type='button';b.setAttribute('aria-label','Назад');b.onclick=back;h.append(b);}h.append(element('h2','',title));parent.append(h);}
  async function load(){const ticket=++epoch,user=getUser();if(!host||!user)return;host.replaceChildren();header(host,'Боты');const top=element('div','botsActions'),createButton=element('button','solid','Создать бота');createButton.type='button';createButton.onclick=renderCreate;top.append(createButton);host.append(top,element('p','muted','Собственные боты Public работают через Bot Core — без Telegram и BotFather.'));const list=element('div','botsList'),loading=element('p','muted','Загружаем ботов…');host.append(list,loading);try{const result=await request('/v1/bots');if(!current(ticket,user.id))return;bots=Array.isArray(result.bots)?result.bots:[];loading.remove();if(!bots.length){list.append(element('p','empty','Ботов пока нет. Создайте первого бота.'));return;}for(const bot of bots)list.append(botCard(bot));}catch(e){if(current(ticket,user.id)){loading.textContent=e.message;loading.classList.add('danger');}}}
  function botCard(bot){const row=element('section','botCard'),main=element('button','botMain'),avatar=element('span','botAvatar','◈'),body=element('span','botText');body.append(element('strong','',bot.name||'Бот'),element('span','muted',bot.status==='active'?'Работает':'Остановлен'));main.append(avatar,body);main.onclick=()=>openBot(bot.id);row.append(main);return row;}
  function renderCreate(){++epoch;if(!host)return;host.replaceChildren();header(host,'Новый бот',load);const form=element('form','botCreateForm'),name=element('input'),label=element('label','','Название'),templates=element('select'),templateLabel=element('label','','Шаблон'),submit=element('button','solid','Создать'),state=element('p');state.dataset.botStatus='';name.required=true;name.maxLength=80;name.placeholder='Например, Запись';for(const [value,text]of [['intake','Заявка'],['help','Справка']]){const o=element('option','',text);o.value=value;templates.append(o);}label.append(name);templateLabel.append(templates);submit.type='submit';form.append(label,templateLabel,submit,element('p','muted','Заявка собирает имя, почту и удобное время. Справка отвечает по готовому меню.'),state);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;submit.disabled=true;state.textContent='Создаём…';try{const bot=await request('/v1/bots',{method:'POST',data:{name:name.value.trim(),template:templates.value,visibility:'private'}});await openBot(bot.id);}catch(err){state.textContent=err.message;state.className='danger';}finally{busy=false;submit.disabled=false;}};host.append(form);}
  async function openBot(id){const ticket=++epoch,user=getUser();if(!host||!user)return;host.replaceChildren();header(host,'Бот',load);const box=element('section','botPanel');box.append(element('p','muted','Загружаем…'));host.append(box);try{const [bot,chats]=await Promise.all([request('/v1/bots/'+id),request('/v1/bots/'+id+'/chats')]);if(!current(ticket,user.id))return;activeBot=bot;box.replaceChildren();const title=element('h3','',bot.name),state=element('p','muted',bot.status==='active'?'Работает':'Остановлен'),buttons=element('div','botsActions'),toggle=element('button','setting',bot.status==='active'?'Остановить':'Включить'),chat=element('button','solid','Открыть переписку');toggle.type=chat.type='button';toggle.onclick=()=>toggleBot(bot);chat.onclick=()=>openChat(bot,chats.chats||[]);buttons.append(chat,toggle);box.append(title,state,buttons,element('p','muted','Бот и его данные доступны только владельцу, пока видимость не изменена.'));}catch(e){if(current(ticket,user.id))box.replaceChildren(element('p','danger',e.message));}}
  async function toggleBot(bot){if(busy)return;busy=true;try{await request('/v1/bots/'+bot.id,{method:'PATCH',data:{revision:bot.revision,status:bot.status==='active'?'stopped':'active'}});await openBot(bot.id);}catch(e){fail(e);}finally{busy=false;}}
  async function openChat(bot,known){const ticket=++epoch,user=getUser();if(!host||!user)return;host.replaceChildren();header(host,bot.name,()=>openBot(bot.id));const thread=element('div','botThread'),choices=element('div','botChoices'),form=element('form','botComposer'),input=element('input','botInput'),send=element('button','solid','Отправить'),note=element('p','muted','Переписка сохраняется в Bot Core отдельно от обычных чатов Public.');input.type='text';input.placeholder='Сообщение боту…';input.maxLength=2000;input.autocomplete='off';send.type='submit';form.append(input,send);host.append(thread,choices,form,note);try{let chat=known[0];if(!chat)chat=await request('/v1/bots/'+bot.id+'/chats',{method:'POST',data:{id:uuid()}});if(!current(ticket,user.id))return;activeBot=bot;activeChat=chat;await paintChat(ticket,thread,choices,form);form.onsubmit=e=>{e.preventDefault();sendMessage(input.value,thread,choices,input,ticket,form);};if(!chat.revision)await sendMessage('/start',thread,choices,input,ticket,form,true);}catch(e){if(current(ticket,user.id))thread.append(element('p','danger',e.message));}}
  async function paintChat(ticket,thread,choices,form){if(!activeChat)return;const h=await request('/v1/chats/'+activeChat.id);if(ticket!==epoch)return;activeChat=h.session;thread.replaceChildren();choices.replaceChildren();let latest=null;for(const event of h.events||[]){thread.append(bubble('me',event.input?.text||''));for(const reply of event.response?.replies||[]){latest=reply;thread.append(bubble('bot',reply.text||''));}}for(const item of latest?.buttons||[]){const b=element('button','botChoice',item.label);b.type='button';b.onclick=()=>sendMessage(item.value||item.id,thread,choices,null,ticket,form);choices.append(b);}const done=/заверш[её]н|нового запроса/i.test(latest?.text||'');form.hidden=done;thread.scrollTop=thread.scrollHeight;}
  const bubble=(kind,text)=>element('div','botBubble '+kind,text);
  async function sendMessage(text,thread,choices,input,ticket,form,silent=false){text=String(text||'').trim();if(!text||busy||!activeChat||activeBot?.status!=='active')return;busy=true;try{await request('/v1/chats/'+activeChat.id+'/messages',{method:'POST',data:{id:uuid(),text,revision:activeChat.revision}});if(input)input.value='';await paintChat(ticket,thread,choices,form);}catch(e){if(!silent)thread.append(element('p','danger',e.message));}finally{busy=false;}}
  function mount(nextHost){host=nextHost;load();}function reset(){++epoch;host=null;bots=[];activeBot=null;activeChat=null;busy=false;}return{mount,reset,refresh:load};
 }global.PablicusBots={create};
})(window);