/* Telegram-like creation flows for Public pre-Stage-3 shell. UI/data stay isolated from message transport. */
(function(){'use strict';
 const STORE={groups:'public:local-groups:v1',contacts:'public:local-contacts:v1',channels:'public:local-channels:v1'};
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const icon=(d)=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+d+'"/></svg>';
 const I={back:'m15 18-6-6 6-6',close:'M6 6l12 12M18 6 6 18',search:'M21 21l-4.35-4.35M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',group:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',contact:'M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8 8a8 8 0 0 0-16 0m16-12v6m-3-3h6',channel:'M4 11v2m2-5v8l10 4V4L6 8Zm10 9 2 2',camera:'M4 7h3l1.5-2h7L17 7h3v12H4V7Zm8 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',qr:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM15 14h2v2h-2zM19 14h2v4h-2zM14 19h4v2h-4z'};
 function host(){let h=$('.publicCreationRoot');if(!h){h=document.createElement('div');h.className='publicCreationRoot';h.hidden=true;document.body.append(h)}return h}
 function close(){const h=host();h.hidden=true;h.replaceChildren();document.body.classList.remove('public-creation-open')}
 function open(html){const h=host();h.innerHTML=html;h.hidden=false;document.body.classList.add('public-creation-open');return h}
 function top(title,{back=false,next='',nextDisabled=false,onBack=close}={}){return '<header class="pcfTop"><button class="pcfRound pcfBack" type="button" aria-label="Назад">'+icon(back?I.back:I.close)+'</button><div class="pcfTopTitle"><strong>'+esc(title)+'</strong></div>'+(next?'<button class="pcfNext" type="button" '+(nextDisabled?'disabled':'')+'>'+esc(next)+'</button>':'<span class="pcfTopSpacer"></span>')+'</header>'}
 function avatarLetter(name){return (String(name||'?').replace('@','').trim()[0]||'?').toUpperCase()}
 function candidates(){const seen=new Set(),out=[];for(const row of all('#screenContent .chatCard')){const name=row.querySelector('.chatText strong')?.textContent?.trim();if(!name||seen.has(name))continue;seen.add(name);out.push({id:name,name,status:row.querySelector('.previewText')?.textContent?.trim()||'был(а) недавно',letter:avatarLetter(name)})}return out}
 function persist(kind,item){const key=STORE[kind],items=read(key);items.unshift(item);write(key,items);window.dispatchEvent(new CustomEvent('public:creation',{detail:{kind,item}}))}
 function shellRow(iconPath,label,kind){return '<button class="pcfAction" type="button" data-kind="'+kind+'"><span class="pcfActionIcon">'+icon(iconPath)+'</span><span>'+esc(label)+'</span></button>'}
 function compose(){const people=candidates();const h=open('<section class="pcfScreen">'+top('Написать сообщение')+'<div class="pcfSearch">'+icon(I.search)+'<input type="search" placeholder="Поиск" autocomplete="off"></div><div class="pcfActions">'+shellRow(I.group,'Создать группу','group')+shellRow(I.contact,'Создать контакт','contact')+shellRow(I.channel,'Создать канал','channel')+'</div><div class="pcfContacts"></div></section>');
  h.querySelector('.pcfBack').onclick=close;const box=h.querySelector('.pcfContacts'),input=h.querySelector('input');
  function paint(){const q=input.value.trim().toLowerCase();box.replaceChildren();for(const p of people.filter(x=>!q||x.name.toLowerCase().includes(q))){const b=document.createElement('button');b.type='button';b.className='pcfPerson';b.innerHTML='<span class="pcfAvatar">'+esc(p.letter)+'</span><span><strong>'+esc(p.name)+'</strong><small>'+esc(p.status)+'</small></span>';b.onclick=()=>{close();const card=all('#screenContent .chatCard').find(r=>r.querySelector('.chatText strong')?.textContent?.trim()===p.name);card?.querySelector('.chatMain')?.click()};box.append(b)}}input.oninput=paint;paint();
  h.querySelector('[data-kind=group]').onclick=groupSelect;h.querySelector('[data-kind=contact]').onclick=contact;h.querySelector('[data-kind=channel]').onclick=channelIntro;setTimeout(()=>input.focus({preventScroll:true}),40)}
 function groupSelect(){const people=candidates(),selected=new Set();const h=open('<section class="pcfScreen">'+top('Группа',{back:true,next:'Далее',nextDisabled:true})+'<div class="pcfCounter">0/200000</div><div class="pcfSearch"><input type="search" placeholder="Кого бы Вы хотели пригласить?" autocomplete="off"></div><div class="pcfPickList"></div></section>');
  h.querySelector('.pcfBack').onclick=compose;const next=h.querySelector('.pcfNext'),box=h.querySelector('.pcfPickList'),input=h.querySelector('input'),counter=h.querySelector('.pcfCounter');
  function paint(){const q=input.value.trim().toLowerCase();box.replaceChildren();let last='';for(const p of people.filter(x=>!q||x.name.toLowerCase().includes(q))){const letter=avatarLetter(p.name);if(letter!==last){const d=document.createElement('div');d.className='pcfLetter';d.textContent=letter;box.append(d);last=letter}const b=document.createElement('button');b.type='button';b.className='pcfPickPerson'+(selected.has(p.id)?' selected':'');b.innerHTML='<span class="pcfCheck">'+(selected.has(p.id)?'✓':'')+'</span><span class="pcfAvatar">'+esc(p.letter)+'</span><span><strong>'+esc(p.name)+'</strong><small>'+esc(p.status)+'</small></span>';b.onclick=()=>{selected.has(p.id)?selected.delete(p.id):selected.add(p.id);counter.textContent=selected.size+'/200000';next.disabled=!selected.size;paint()};box.append(b)}}input.oninput=paint;paint();next.onclick=()=>groupDetails(people.filter(p=>selected.has(p.id)));}
 function photoControl(){return '<label class="pcfPhoto"><span>'+icon(I.camera)+'</span><input type="file" accept="image/*" hidden></label>'}
 function readPhoto(input,cb){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>cb(String(r.result||''));r.readAsDataURL(f)}
 function groupDetails(members){const h=open('<section class="pcfScreen pcfSoft">'+top('Новая группа',{back:true,next:'Создать',nextDisabled:true})+'<div class="pcfIdentityCard">'+photoControl()+'<input class="pcfTitleInput" maxlength="80" placeholder="Название группы"></div><p class="pcfHint">Участников: '+members.length+'</p></section>');h.querySelector('.pcfBack').onclick=groupSelect;const name=h.querySelector('.pcfTitleInput'),next=h.querySelector('.pcfNext'),photo=h.querySelector('.pcfPhoto'),file=photo.querySelector('input');let avatar='';file.onchange=()=>readPhoto(file,data=>{avatar=data;photo.style.backgroundImage='url("'+data.replace(/"/g,'%22')+'")';photo.classList.add('has-photo')});name.oninput=()=>next.disabled=!name.value.trim();next.onclick=()=>{const item={id:crypto.randomUUID(),title:name.value.trim(),memberNames:members.map(x=>x.name),avatar,createdAt:Date.now()};persist('groups',item);close();addLocalEntity(item,'Группа · '+members.length+' участников');notify('Группа создана')};setTimeout(()=>name.focus(),50)}
 function contact(){const h=open('<section class="pcfScreen pcfSoft">'+top('Новый контакт',{next:'✓',nextDisabled:true})+'<div class="pcfContactName"><input data-f="first" placeholder="Имя"><input data-f="last" placeholder="Фамилия"></div><div class="pcfPhoneCard"><button type="button" class="pcfCountry">🇷🇺 <span>Россия</span><b>›</b></button><div class="pcfPhone"><span>+7</span><input inputmode="tel" autocomplete="tel" placeholder="000 000 0000"></div></div><label class="pcfToggle"><span>Синхронизировать с телефоном</span><input type="checkbox" checked><i></i></label><button class="pcfQr" type="button">'+icon(I.qr)+'<span>Добавить по QR-коду</span></button></section>');h.querySelector('.pcfBack').onclick=close;const first=h.querySelector('[data-f=first]'),last=h.querySelector('[data-f=last]'),phone=h.querySelector('.pcfPhone input'),next=h.querySelector('.pcfNext');const valid=()=>next.disabled=!first.value.trim()||phone.value.replace(/\D/g,'').length<7;first.oninput=phone.oninput=valid;next.onclick=()=>{const item={id:crypto.randomUUID(),first:first.value.trim(),last:last.value.trim(),phone:'+7'+phone.value.replace(/\D/g,''),sync:h.querySelector('.pcfToggle input').checked,createdAt:Date.now()};persist('contacts',item);close();notify('Контакт сохранён')};h.querySelector('.pcfQr').onclick=()=>notify('QR-сканер будет подключён к камере устройства');setTimeout(()=>first.focus(),50)}
 function channelIntro(){const h=open('<section class="pcfScreen pcfSoft pcfChannelIntro">'+top('',{back:true})+'<div class="pcfChannelGraphic"><div class="pcfPhoneMock"><span></span><div></div><div></div><div></div></div><i>Channel<br><small>57k members</small></i><b>views<br><small>647</small></b></div><h1>Что такое канал?</h1><p>Каналы — инструмент, который позволяет транслировать сообщения на большую аудиторию.</p><button class="pcfPrimary" type="button">Создать канал</button></section>');h.querySelector('.pcfBack').onclick=compose;h.querySelector('.pcfPrimary').onclick=channelDetails}
 function channelDetails(){const h=open('<section class="pcfScreen pcfSoft">'+top('Создать канал',{back:true,next:'Далее',nextDisabled:true})+'<div class="pcfIdentityCard">'+photoControl()+'<input class="pcfTitleInput" maxlength="80" placeholder="Название канала"></div><div class="pcfDescription"><textarea maxlength="255" placeholder="Описание"></textarea></div><p class="pcfHint">Можете указать дополнительное описание канала.</p></section>');h.querySelector('.pcfBack').onclick=channelIntro;const title=h.querySelector('.pcfTitleInput'),next=h.querySelector('.pcfNext'),photo=h.querySelector('.pcfPhoto'),file=photo.querySelector('input');let avatar='';file.onchange=()=>readPhoto(file,data=>{avatar=data;photo.style.backgroundImage='url("'+data.replace(/"/g,'%22')+'")';photo.classList.add('has-photo')});title.oninput=()=>next.disabled=!title.value.trim();next.onclick=()=>{const item={id:crypto.randomUUID(),title:title.value.trim(),description:h.querySelector('textarea').value.trim(),avatar,createdAt:Date.now()};persist('channels',item);close();addLocalEntity(item,'Канал');notify('Канал создан')};setTimeout(()=>title.focus(),50)}
 function notify(text){const t=document.getElementById('toast');if(!t)return;t.textContent=text;t.hidden=false;clearTimeout(notify.t);notify.t=setTimeout(()=>t.hidden=true,2400)}
 function addLocalEntity(item,subtitle){const content=document.getElementById('screenContent');if(!content||document.getElementById('local-'+item.id))return;const row=document.createElement('section');row.className='chatCard publicLocalEntity';row.id='local-'+item.id;row.innerHTML='<button class="chatMain" type="button"><span class="avatar">'+esc(avatarLetter(item.title))+'</span><span class="chatText"><strong>'+esc(item.title)+'</strong><span class="previewText">'+esc(subtitle)+'</span></span></button><button class="focusBtn" aria-label="Добавить в избранное">☆</button>';if(item.avatar){const a=row.querySelector('.avatar');a.textContent='';a.style.backgroundImage='url("'+item.avatar.replace(/"/g,'%22')+'")';a.style.backgroundSize='cover';a.style.backgroundPosition='center'}row.querySelector('.chatMain').onclick=()=>notify('Создано. Подключение групповых сообщений идёт отдельным транспортным слоем.');const f=row.querySelector('.focusBtn');f.onclick=()=>{f.textContent=f.textContent==='☆'?'★':'☆';f.setAttribute('aria-label',f.textContent==='★'?'Убрать из избранного':'Добавить в избранное')};content.prepend(row)}
 function restore(){if(document.body.dataset.creationRestored)return;document.body.dataset.creationRestored='1';for(const x of read(STORE.groups))addLocalEntity(x,'Группа · '+(x.memberNames?.length||0)+' участников');for(const x of read(STORE.channels))addLocalEntity(x,'Канал')}
 document.addEventListener('click',e=>{const edit=e.target.closest('.publicHomeActions .publicTopIcon[aria-label="Создать"]');if(edit){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();compose();return}const legacy=e.target.closest('.publicCreateMenu [data-kind]');if(legacy){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const k=legacy.dataset.kind;k==='group'?groupSelect():k==='contact'?contact():channelIntro()}},true);
 new MutationObserver(()=>{if(document.body.dataset.page==='chats'||document.getElementById('home')?.dataset.page==='chats')restore()}).observe(document.body,{subtree:true,childList:true,attributes:true});setTimeout(restore,300);
})();