/* Gesture-first media viewer: swipe to navigate/close, long press for actions. */
(function(scope){'use strict';let activeViewer=null;
 function safeUrl(value){if(typeof value!=='string')return null;try{const u=new scope.URL(value);return['https:','http:','blob:'].includes(u.protocol)?u.href:null}catch{return null}}
 function create(options={}){const document=scope.document;if(!document||typeof options.resolveUrl!=='function')throw Error('Для просмотра вложений нужен обработчик загрузки.');
  const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n};
  const dialog=el('dialog','pablicusMediaViewer'),stage=el('div','pmvStage'),notice=el('div','pmvNotice'),status=el('p','pmvStatus'),retry=el('button','pmvRetry','Повторить'),menu=el('div','pmvContextMenu');
  retry.type='button';notice.append(status,retry);menu.hidden=true;dialog.append(stage,notice,menu);dialog.setAttribute('aria-label','Просмотр фото и видео');
  let items=[],index=0,epoch=0,opened=false,destroyed=false,currentMedia=null,restoreFocus=null,oldBodyOverflow='',touch=null,holdTimer=0;
  function setStatus(text,canRetry=false){status.textContent=text||'';retry.hidden=!canRetry;notice.hidden=!text&&!canRetry}
  function release(){if(currentMedia){currentMedia.onload=currentMedia.onerror=currentMedia.onloadedmetadata=currentMedia.onplaying=null;if(currentMedia.tagName==='VIDEO'){currentMedia.pause();currentMedia.removeAttribute('src');currentMedia.load()}else currentMedia.removeAttribute('src')}currentMedia=null;stage.replaceChildren()}
  function hideMenu(){menu.hidden=true;menu.replaceChildren()}
  async function shareCurrent(){const item=items[index];if(!item)return;try{const url=safeUrl(await options.resolveUrl(item));if(!url)throw Error('Нет адреса файла');if(navigator.share)await navigator.share({title:item.name||'',url});else if(navigator.clipboard)await navigator.clipboard.writeText(url)}catch(e){if(typeof options.onError==='function')options.onError(e)}}
  async function saveCurrent(){const item=items[index];if(!item||typeof options.download!=='function')return;try{await options.download(item)}catch(e){if(typeof options.onError==='function')options.onError(e)}}
  function openMenu(x,y){hideMenu();const add=(label,fn)=>{const b=el('button','pmvContextAction',label);b.type='button';b.onclick=async()=>{hideMenu();await fn()};menu.append(b)};if(typeof options.download==='function')add('Сохранить',saveCurrent);add('Поделиться',shareCurrent);if(typeof options.onReply==='function')add('Ответить',async()=>{const item=items[index];close();await options.onReply(item)});menu.style.left=Math.max(12,Math.min(x,innerWidth-230))+'px';menu.style.top=Math.max(70,Math.min(y,innerHeight-190))+'px';menu.hidden=false}
  async function show(target){if(!opened||destroyed||target<0||target>=items.length)return;const ticket=++epoch;index=target;release();hideMenu();touch=null;setStatus('Загрузка…');const item=items[index];try{const resolved=await options.resolveUrl(item);if(!opened||ticket!==epoch||destroyed)return;const url=safeUrl(resolved);if(!url)throw Error('Не удалось получить адрес вложения.');const media=el(item.type==='image'?'img':'video','pmvMedia');currentMedia=media;const ready=()=>{if(opened&&ticket===epoch&&media===currentMedia)setStatus('')};media.onerror=()=>{if(opened&&ticket===epoch)setStatus('Не удалось открыть вложение.',true)};if(item.type==='image'){media.alt='';media.draggable=false;media.onload=ready}else{media.controls=true;media.playsInline=true;media.preload='metadata';media.onloadedmetadata=ready;media.onplaying=ready}stage.append(media);media.src=url}catch(e){if(opened&&ticket===epoch){setStatus('Не удалось загрузить вложение.',true);if(typeof options.onError==='function')options.onError(e)}}}
  function cleanClose(){if(!opened)return;opened=false;++epoch;clearTimeout(holdTimer);touch=null;hideMenu();release();items=[];setStatus('');document.body.style.overflow=oldBodyOverflow;if(activeViewer===api)activeViewer=null;restoreFocus=null}
  function close(){if(!opened)return;if(dialog.open&&typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');cleanClose()}
  async function open(value,selected){if(destroyed)throw Error('Просмотр уже закрыт.');const next=Array.isArray(value)?value.filter(i=>i&&['image','video'].includes(i.type)).map(i=>({...i})):[];if(!next.length)throw Error('Фото или видео не найдено.');if(activeViewer&&activeViewer!==api)activeViewer.close();scope.PablicusRichMessage?.stopAll?.();if(!dialog.isConnected)document.body.append(dialog);restoreFocus=document.activeElement;oldBodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';opened=true;activeViewer=api;try{dialog.showModal?dialog.showModal():dialog.setAttribute('open','')}catch(e){cleanClose();throw e}items=next;await show(Number.isInteger(selected)?Math.min(Math.max(selected,0),items.length-1):0)}
  retry.onclick=()=>show(index);dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('close',()=>{if(!dialog.open)cleanClose()});dialog.addEventListener('click',e=>{if(!menu.hidden&&!menu.contains(e.target)){hideMenu();return}if(e.target!==currentMedia&&e.target!==stage)return;if(items.length<2)return;const x=e.clientX/innerWidth;if(x<.34&&index>0)show(index-1);else if(x>.66&&index<items.length-1)show(index+1)});
  stage.addEventListener('touchstart',e=>{hideMenu();clearTimeout(holdTimer);if(e.touches.length!==1||scope.visualViewport?.scale>1.05){touch=null;return}const p=e.touches[0];touch={x:p.clientX,y:p.clientY,t:Date.now(),moved:false};holdTimer=setTimeout(()=>{if(touch&&!touch.moved)openMenu(touch.x,touch.y)},520)},{passive:true});
  stage.addEventListener('touchmove',e=>{if(!touch||e.touches.length!==1)return;const p=e.touches[0],dx=p.clientX-touch.x,dy=p.clientY-touch.y;if(Math.hypot(dx,dy)>14){touch.moved=true;clearTimeout(holdTimer)}},{passive:true});
  stage.addEventListener('touchend',e=>{clearTimeout(holdTimer);const s=touch;touch=null;if(!s||!e.changedTouches.length||Date.now()-s.t>900)return;const p=e.changedTouches[0],dx=p.clientX-s.x,dy=p.clientY-s.y;if(Math.abs(dy)>90&&Math.abs(dy)>Math.abs(dx)*1.15){close();return}if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.25){const next=index+(dx<0?1:-1);if(next>=0&&next<items.length)show(next)}} ,{passive:true});
  stage.addEventListener('touchcancel',()=>{clearTimeout(holdTimer);touch=null},{passive:true});
  stage.addEventListener('contextmenu',e=>{e.preventDefault();openMenu(e.clientX,e.clientY)});
  const api={open,close,destroy(){close();destroyed=true;dialog.remove()},get opened(){return opened}};return api}
 scope.PablicusMediaViewer=Object.freeze({create});
})(typeof window!=='undefined'?window:globalThis);